/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { articlesGetById } from "../funcs/articlesGetById.js";
import { articlesListPaginated } from "../funcs/articlesListPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Articles extends ClientSDK {
  /**
   * Get article by ID
   *
   * @remarks
   * Retrieves detailed information about a specific article
   */
  async getById(
    request: operations.ArticleGetArticleByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(articlesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get paginated articles
   *
   * @remarks
   * Retrieves a paginated list of articles
   */
  async listPaginated(
    request: operations.ArticleGetArticlesPaginatedRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(articlesListPaginated(
      this,
      request,
      options,
    ));
  }
}
