/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { articlesGet } from "../funcs/articlesGet.js";
import { articlesGetPaginated } from "../funcs/articlesGetPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Articles extends ClientSDK {
  /**
   * Get article by ID
   *
   * @remarks
   * Retrieves detailed information about a specific article
   */
  async get(
    request?: operations.ArticleGetArticleByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(articlesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get paginated articles
   *
   * @remarks
   * Retrieves a paginated list of articles
   */
  async getPaginated(
    request?: operations.ArticleGetArticlesPaginatedRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(articlesGetPaginated(
      this,
      request,
      options,
    ));
  }
}
