/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { battleRankingsGet } from "../funcs/battleRankingsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BattleRankings extends ClientSDK {
  /**
   * Get battle rankings
   *
   * @remarks
   * Retrieves damage, ground, or money rankings for users or countries in battles, rounds, or wars
   */
  async get(
    request?: operations.BattleRankingGetRankingRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(battleRankingsGet(
      this,
      request,
      options,
    ));
  }
}
