/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { battlesGetById } from "../funcs/battlesGetById.js";
import { battlesGetLiveData } from "../funcs/battlesGetLiveData.js";
import { battlesList } from "../funcs/battlesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Battles extends ClientSDK {
  /**
   * Get battle by ID
   *
   * @remarks
   * Retrieves detailed information about a specific battle
   */
  async getById(
    request: operations.BattleGetByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(battlesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get live battle data
   *
   * @remarks
   * Retrieves real-time battle data including current round information
   */
  async getLiveData(
    request: operations.BattleGetLiveBattleDataRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(battlesGetLiveData(
      this,
      request,
      options,
    ));
  }

  /**
   * Get battles
   *
   * @remarks
   * Retrieves a list of battles
   */
  async list(
    request?: operations.BattleGetBattlesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(battlesList(
      this,
      request,
      options,
    ));
  }
}
