/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { companiesGetAll } from "../funcs/companiesGetAll.js";
import { companiesGetById } from "../funcs/companiesGetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Companies extends ClientSDK {
  /**
   * Get company by ID
   *
   * @remarks
   * Retrieves detailed information about a specific company
   */
  async getById(
    request?: operations.CompanyGetByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(companiesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get companies with pagination
   *
   * @remarks
   * Retrieves a paginated list of companies with optional filtering
   */
  async getAll(
    request?: operations.CompanyGetCompaniesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(companiesGetAll(
      this,
      request,
      options,
    ));
  }
}
