/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { countriesGetAll } from "../funcs/countriesGetAll.js";
import { countriesGetById } from "../funcs/countriesGetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Countries extends ClientSDK {
  /**
   * Get country by ID
   *
   * @remarks
   * Retrieves detailed information about a specific country
   */
  async getById(
    request?: operations.CountryGetCountryByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(countriesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all countries
   *
   * @remarks
   * Retrieves a list of all available countries
   */
  async getAll(
    request?: operations.CountryGetAllCountriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(countriesGetAll(
      this,
      request,
      options,
    ));
  }
}
