/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetPaginated } from "../funcs/eventsGetPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * Get paginated events
   *
   * @remarks
   * Retrieves a paginated list of events with optional country filter
   */
  async getPaginated(
    request?: operations.EventGetEventsPaginatedRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(eventsGetPaginated(
      this,
      request,
      options,
    ));
  }
}
