/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gameConfigGet } from "../funcs/gameConfigGet.js";
import { gameConfigGetDates } from "../funcs/gameConfigGetDates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GameConfig extends ClientSDK {
  /**
   * Get game dates
   *
   * @remarks
   * Retrieves game-related dates and timings
   */
  async getDates(
    request?: operations.GameConfigGetDatesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(gameConfigGetDates(
      this,
      request,
      options,
    ));
  }

  /**
   * Get game configuration
   *
   * @remarks
   * Retrieves static game configuration
   */
  async get(
    request?: operations.GameConfigGetGameConfigRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(gameConfigGet(
      this,
      request,
      options,
    ));
  }
}
