/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gameConfigsGet } from "../funcs/gameConfigsGet.js";
import { gameConfigsGetDates } from "../funcs/gameConfigsGetDates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GameConfigs extends ClientSDK {
  /**
   * Get game dates
   *
   * @remarks
   * Retrieves game-related dates and timings
   */
  async getDates(
    request?: operations.GameConfigGetDatesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(gameConfigsGetDates(
      this,
      request,
      options,
    ));
  }

  /**
   * Get game configuration
   *
   * @remarks
   * Retrieves static game configuration
   */
  async get(
    request?: operations.GameConfigGetGameConfigRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(gameConfigsGet(
      this,
      request,
      options,
    ));
  }
}
