/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { governmentsGetByCountryId } from "../funcs/governmentsGetByCountryId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Governments extends ClientSDK {
  /**
   * Get government by country ID
   *
   * @remarks
   * Retrieves government information for a specific country
   */
  async getByCountryId(
    request?: operations.GovernmentGetByCountryIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(governmentsGetByCountryId(
      this,
      request,
      options,
    ));
  }
}
