/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { itemOffersGet } from "../funcs/itemOffersGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ItemOffers extends ClientSDK {
  /**
   * Get item offer by ID
   *
   * @remarks
   * Retrieves detailed information about a specific item offer
   */
  async get(
    request?: operations.ItemOfferGetByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(itemOffersGet(
      this,
      request,
      options,
    ));
  }
}
