/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { itemTradingsGetPrices } from "../funcs/itemTradingsGetPrices.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ItemTradings extends ClientSDK {
  /**
   * Get item prices
   *
   * @remarks
   * Retrieves current market prices for all tradeable items
   */
  async getPrices(
    request?: operations.ItemTradingGetPricesRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(itemTradingsGetPrices(
      this,
      request,
      options,
    ));
  }
}
