/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { militaryUnitsGetPaginated } from "../funcs/militaryUnitsGetPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class MilitaryUnits extends ClientSDK {
  /**
   * Get military units (paginated)
   *
   * @remarks
   * Retrieves a paginated list of military units with optional filters
   */
  async getPaginated(
    request?: operations.MuGetManyPaginatedRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(militaryUnitsGetPaginated(
      this,
      request,
      options,
    ));
  }
}
