/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { musGet } from "../funcs/musGet.js";
import { musGetPaginated } from "../funcs/musGetPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mus extends ClientSDK {
  /**
   * Get military unit by ID
   *
   * @remarks
   * Retrieves detailed information about a specific military unit
   */
  async get(
    request?: operations.MuGetByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(musGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get military units (paginated)
   *
   * @remarks
   * Retrieves a paginated list of military units with optional filters
   */
  async getPaginated(
    request?: operations.MuGetManyPaginatedRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(musGetPaginated(
      this,
      request,
      options,
    ));
  }
}
