/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { musGetById } from "../funcs/musGetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mus extends ClientSDK {
  /**
   * Get military unit by ID
   *
   * @remarks
   * Retrieves detailed information about a specific military unit
   */
  async getById(
    request: operations.MuGetByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(musGetById(
      this,
      request,
      options,
    ));
  }
}
