/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rankingsGet } from "../funcs/rankingsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rankings extends ClientSDK {
  /**
   * Get ranking data
   *
   * @remarks
   * Retrieves ranking data for the specified ranking type and optional year-week filter
   */
  async get(
    request?: operations.RankingGetRankingRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(rankingsGet(
      this,
      request,
      options,
    ));
  }
}
