/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { regionsGetById } from "../funcs/regionsGetById.js";
import { regionsList } from "../funcs/regionsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Regions extends ClientSDK {
  /**
   * Get region by ID
   *
   * @remarks
   * Retrieves detailed information about a specific region
   */
  async getById(
    request: operations.RegionGetByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(regionsGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all regions
   *
   * @remarks
   * Retrieves a complete object containing all available regions
   */
  async list(
    request?: operations.RegionGetRegionsObjectRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(regionsList(
      this,
      request,
      options,
    ));
  }
}
