/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { regionsGetAll } from "../funcs/regionsGetAll.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Regions extends ClientSDK {
  /**
   * Get all regions
   *
   * @remarks
   * Retrieves a complete object containing all available regions
   */
  async getAll(
    request?: operations.RegionGetRegionsObjectRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(regionsGetAll(
      this,
      request,
      options,
    ));
  }
}
