/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { regionGetById } from "../funcs/regionGetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Region extends ClientSDK {
  /**
   * Get region by ID
   *
   * @remarks
   * Retrieves detailed information about a specific region
   */
  async getById(
    request?: operations.RegionGetByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(regionGetById(
      this,
      request,
      options,
    ));
  }
}
