/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { roundGetLastHits } from "../funcs/roundGetLastHits.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Round extends ClientSDK {
  /**
   * Get last hits in round
   *
   * @remarks
   * Retrieves the most recent hits/damages in a specific battle round
   */
  async getLastHits(
    request: operations.RoundGetLastHitsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(roundGetLastHits(
      this,
      request,
      options,
    ));
  }
}
