/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { roundsGetById } from "../funcs/roundsGetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rounds extends ClientSDK {
  /**
   * Get round by ID
   *
   * @remarks
   * Retrieves detailed information about a specific battle round
   */
  async getById(
    request: operations.RoundGetByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(roundsGetById(
      this,
      request,
      options,
    ));
  }
}
