/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { roundsGet } from "../funcs/roundsGet.js";
import { roundsGetLastHits } from "../funcs/roundsGetLastHits.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rounds extends ClientSDK {
  /**
   * Get round by ID
   *
   * @remarks
   * Retrieves detailed information about a specific battle round
   */
  async get(
    request?: operations.RoundGetByIdRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(roundsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get last hits in round
   *
   * @remarks
   * Retrieves the most recent hits/damages in a specific battle round
   */
  async getLastHits(
    request?: operations.RoundGetLastHitsRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(roundsGetLastHits(
      this,
      request,
      options,
    ));
  }
}
