/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Articles } from "./articles.js";
import { BattleRankings } from "./battlerankings.js";
import { Battles } from "./battles.js";
import { Companies } from "./companies.js";
import { Countries } from "./countries.js";
import { Events } from "./events.js";
import { GameConfigs } from "./gameconfigs.js";
import { Governments } from "./governments.js";
import { ItemOffers } from "./itemoffers.js";
import { ItemTradings } from "./itemtradings.js";
import { Mus } from "./mus.js";
import { Rankings } from "./rankings.js";
import { Region } from "./region.js";
import { Regions } from "./regions.js";
import { Rounds } from "./rounds.js";
import { Search } from "./search.js";
import { TradingOrders } from "./tradingorders.js";
import { Transactions } from "./transactions.js";
import { Upgrades } from "./upgrades.js";
import { Users } from "./users.js";
import { WorkOffers } from "./workoffers.js";

export class Warera extends ClientSDK {
  private _companies?: Companies;
  get companies(): Companies {
    return (this._companies ??= new Companies(this._options));
  }

  private _countries?: Countries;
  get countries(): Countries {
    return (this._countries ??= new Countries(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _governments?: Governments;
  get governments(): Governments {
    return (this._governments ??= new Governments(this._options));
  }

  private _region?: Region;
  get region(): Region {
    return (this._region ??= new Region(this._options));
  }

  private _regions?: Regions;
  get regions(): Regions {
    return (this._regions ??= new Regions(this._options));
  }

  private _battles?: Battles;
  get battles(): Battles {
    return (this._battles ??= new Battles(this._options));
  }

  private _rounds?: Rounds;
  get rounds(): Rounds {
    return (this._rounds ??= new Rounds(this._options));
  }

  private _battleRankings?: BattleRankings;
  get battleRankings(): BattleRankings {
    return (this._battleRankings ??= new BattleRankings(this._options));
  }

  private _itemTradings?: ItemTradings;
  get itemTradings(): ItemTradings {
    return (this._itemTradings ??= new ItemTradings(this._options));
  }

  private _tradingOrders?: TradingOrders;
  get tradingOrders(): TradingOrders {
    return (this._tradingOrders ??= new TradingOrders(this._options));
  }

  private _itemOffers?: ItemOffers;
  get itemOffers(): ItemOffers {
    return (this._itemOffers ??= new ItemOffers(this._options));
  }

  private _workOffers?: WorkOffers;
  get workOffers(): WorkOffers {
    return (this._workOffers ??= new WorkOffers(this._options));
  }

  private _rankings?: Rankings;
  get rankings(): Rankings {
    return (this._rankings ??= new Rankings(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }

  private _gameConfigs?: GameConfigs;
  get gameConfigs(): GameConfigs {
    return (this._gameConfigs ??= new GameConfigs(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }

  private _articles?: Articles;
  get articles(): Articles {
    return (this._articles ??= new Articles(this._options));
  }

  private _mus?: Mus;
  get mus(): Mus {
    return (this._mus ??= new Mus(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }

  private _upgrades?: Upgrades;
  get upgrades(): Upgrades {
    return (this._upgrades ??= new Upgrades(this._options));
  }
}
