/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchGlobal } from "../funcs/searchGlobal.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Global search
   *
   * @remarks
   * Performs a global search across users, companies, articles, and other entities
   */
  async global(
    request: operations.SearchSearchAnythingRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(searchGlobal(
      this,
      request,
      options,
    ));
  }
}
