/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tradingOrdersGetTop } from "../funcs/tradingOrdersGetTop.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TradingOrders extends ClientSDK {
  /**
   * Get best orders for an item
   *
   * @remarks
   * Retrieves the best orders for an item
   */
  async getTop(
    request: operations.TradingOrderGetTopOrdersRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(tradingOrdersGetTop(
      this,
      request,
      options,
    ));
  }
}
