/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsListPaginated } from "../funcs/transactionsListPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * Get paginated transactions
   *
   * @remarks
   * Retrieves a paginated list of transactions
   */
  async listPaginated(
    request?: operations.TransactionGetPaginatedTransactionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(transactionsListPaginated(
      this,
      request,
      options,
    ));
  }
}
