/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { upgradesGetByTypeAndEntity } from "../funcs/upgradesGetByTypeAndEntity.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Upgrades extends ClientSDK {
  /**
   * Get upgrade by type and entity
   *
   * @remarks
   * Retrieves upgrade information for a specific upgrade type and entity (region, company, or military unit)
   */
  async getByTypeAndEntity(
    request?: operations.UpgradeGetUpgradeByTypeAndEntityRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(upgradesGetByTypeAndEntity(
      this,
      request,
      options,
    ));
  }
}
