/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetByCountry } from "../funcs/usersGetByCountry.js";
import { usersGetLite } from "../funcs/usersGetLite.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Users extends ClientSDK {
  /**
   * Get user profile (lite)
   *
   * @remarks
   * Retrieves basic public information about a user including username, skills, and rankings
   */
  async getLite(
    request?: operations.UserGetUserLiteRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersGetLite(
      this,
      request,
      options,
    ));
  }

  /**
   * Get users by country
   *
   * @remarks
   * Retrieves a list of users by country
   */
  async getByCountry(
    request?: operations.UserGetUsersByCountryRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersGetByCountry(
      this,
      request,
      options,
    ));
  }
}
