/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workOffersGetByCompanyId } from "../funcs/workOffersGetByCompanyId.js";
import { workOffersGetById } from "../funcs/workOffersGetById.js";
import { workOffersGetPaginated } from "../funcs/workOffersGetPaginated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class WorkOffers extends ClientSDK {
  /**
   * Get work offer by ID
   *
   * @remarks
   * Retrieves detailed information about a specific work offer
   */
  async getById(
    request: operations.WorkOfferGetByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(workOffersGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get work offer by company ID
   *
   * @remarks
   * Retrieves work offer for a specific company
   */
  async getByCompanyId(
    request: operations.WorkOfferGetWorkOfferByCompanyIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(workOffersGetByCompanyId(
      this,
      request,
      options,
    ));
  }

  /**
   * Get paginated work offers
   *
   * @remarks
   * Retrieves a paginated list of work offers with optional user and region filtering
   */
  async getPaginated(
    request?: operations.WorkOfferGetWorkOffersPaginatedRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(workOffersGetPaginated(
      this,
      request,
      options,
    ));
  }
}
