/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @thegamefatherco/warera-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx companiesGetById.example.ts
 */

import { Warera } from "@thegamefatherco/warera-sdk";

const warera = new Warera({
  serverURL: "https://api.example.com",
});

async function main() {
  await warera.companies.getById();
}

main().catch(console.error);
