/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type of articles to get
 */
export const ArticleGetArticlesPaginatedType = {
  Weekly: "weekly",
  Top: "top",
  My: "my",
  Subscriptions: "subscriptions",
  Last: "last",
} as const;
/**
 * The type of articles to get
 */
export type ArticleGetArticlesPaginatedType = ClosedEnum<
  typeof ArticleGetArticlesPaginatedType
>;

export type ArticleGetArticlesPaginatedInput = {
  /**
   * The type of articles to get
   */
  type: ArticleGetArticlesPaginatedType;
  /**
   * The limit of articles to get
   */
  limit?: number | undefined;
  cursor?: string | undefined;
  /**
   * The user ID to get articles for
   */
  userId?: string | undefined;
  /**
   * The categories to get articles for
   */
  categories?: Array<string> | undefined;
  /**
   * The languages to get articles for
   */
  languages?: Array<string> | undefined;
};

export type ArticleGetArticlesPaginatedRequest = {
  /**
   * JSON-encoded input parameters
   */
  input: ArticleGetArticlesPaginatedInput;
};

/** @internal */
export const ArticleGetArticlesPaginatedType$inboundSchema: z.ZodMiniEnum<
  typeof ArticleGetArticlesPaginatedType
> = z.enum(ArticleGetArticlesPaginatedType);
/** @internal */
export const ArticleGetArticlesPaginatedType$outboundSchema: z.ZodMiniEnum<
  typeof ArticleGetArticlesPaginatedType
> = ArticleGetArticlesPaginatedType$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleGetArticlesPaginatedType$ {
  /** @deprecated use `ArticleGetArticlesPaginatedType$inboundSchema` instead. */
  export const inboundSchema = ArticleGetArticlesPaginatedType$inboundSchema;
  /** @deprecated use `ArticleGetArticlesPaginatedType$outboundSchema` instead. */
  export const outboundSchema = ArticleGetArticlesPaginatedType$outboundSchema;
}

/** @internal */
export const ArticleGetArticlesPaginatedInput$inboundSchema: z.ZodMiniType<
  ArticleGetArticlesPaginatedInput,
  unknown
> = z.object({
  type: ArticleGetArticlesPaginatedType$inboundSchema,
  limit: z._default(types.number(), 10),
  cursor: types.optional(types.string()),
  userId: types.optional(types.string()),
  categories: types.optional(z.array(types.string())),
  languages: types.optional(z.array(types.string())),
});
/** @internal */
export type ArticleGetArticlesPaginatedInput$Outbound = {
  type: string;
  limit: number;
  cursor?: string | undefined;
  userId?: string | undefined;
  categories?: Array<string> | undefined;
  languages?: Array<string> | undefined;
};

/** @internal */
export const ArticleGetArticlesPaginatedInput$outboundSchema: z.ZodMiniType<
  ArticleGetArticlesPaginatedInput$Outbound,
  ArticleGetArticlesPaginatedInput
> = z.object({
  type: ArticleGetArticlesPaginatedType$outboundSchema,
  limit: z._default(z.number(), 10),
  cursor: z.optional(z.string()),
  userId: z.optional(z.string()),
  categories: z.optional(z.array(z.string())),
  languages: z.optional(z.array(z.string())),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleGetArticlesPaginatedInput$ {
  /** @deprecated use `ArticleGetArticlesPaginatedInput$inboundSchema` instead. */
  export const inboundSchema = ArticleGetArticlesPaginatedInput$inboundSchema;
  /** @deprecated use `ArticleGetArticlesPaginatedInput$outboundSchema` instead. */
  export const outboundSchema = ArticleGetArticlesPaginatedInput$outboundSchema;
  /** @deprecated use `ArticleGetArticlesPaginatedInput$Outbound` instead. */
  export type Outbound = ArticleGetArticlesPaginatedInput$Outbound;
}

export function articleGetArticlesPaginatedInputToJSON(
  articleGetArticlesPaginatedInput: ArticleGetArticlesPaginatedInput,
): string {
  return JSON.stringify(
    ArticleGetArticlesPaginatedInput$outboundSchema.parse(
      articleGetArticlesPaginatedInput,
    ),
  );
}
export function articleGetArticlesPaginatedInputFromJSON(
  jsonString: string,
): SafeParseResult<ArticleGetArticlesPaginatedInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArticleGetArticlesPaginatedInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArticleGetArticlesPaginatedInput' from JSON`,
  );
}

/** @internal */
export const ArticleGetArticlesPaginatedRequest$inboundSchema: z.ZodMiniType<
  ArticleGetArticlesPaginatedRequest,
  unknown
> = z.object({
  input: z.lazy(() => ArticleGetArticlesPaginatedInput$inboundSchema),
});
/** @internal */
export type ArticleGetArticlesPaginatedRequest$Outbound = {
  input: ArticleGetArticlesPaginatedInput$Outbound;
};

/** @internal */
export const ArticleGetArticlesPaginatedRequest$outboundSchema: z.ZodMiniType<
  ArticleGetArticlesPaginatedRequest$Outbound,
  ArticleGetArticlesPaginatedRequest
> = z.object({
  input: z.lazy(() => ArticleGetArticlesPaginatedInput$outboundSchema),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleGetArticlesPaginatedRequest$ {
  /** @deprecated use `ArticleGetArticlesPaginatedRequest$inboundSchema` instead. */
  export const inboundSchema = ArticleGetArticlesPaginatedRequest$inboundSchema;
  /** @deprecated use `ArticleGetArticlesPaginatedRequest$outboundSchema` instead. */
  export const outboundSchema =
    ArticleGetArticlesPaginatedRequest$outboundSchema;
  /** @deprecated use `ArticleGetArticlesPaginatedRequest$Outbound` instead. */
  export type Outbound = ArticleGetArticlesPaginatedRequest$Outbound;
}

export function articleGetArticlesPaginatedRequestToJSON(
  articleGetArticlesPaginatedRequest: ArticleGetArticlesPaginatedRequest,
): string {
  return JSON.stringify(
    ArticleGetArticlesPaginatedRequest$outboundSchema.parse(
      articleGetArticlesPaginatedRequest,
    ),
  );
}
export function articleGetArticlesPaginatedRequestFromJSON(
  jsonString: string,
): SafeParseResult<ArticleGetArticlesPaginatedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ArticleGetArticlesPaginatedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArticleGetArticlesPaginatedRequest' from JSON`,
  );
}
