/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of articles to get
 */
export const ArticleGetArticlesPaginatedType = {
  Weekly: "weekly",
  Top: "top",
  My: "my",
  Subscriptions: "subscriptions",
  Last: "last",
} as const;
/**
 * The type of articles to get
 */
export type ArticleGetArticlesPaginatedType = ClosedEnum<
  typeof ArticleGetArticlesPaginatedType
>;

export type ArticleGetArticlesPaginatedRequest = {
  /**
   * The type of articles to get
   */
  type: ArticleGetArticlesPaginatedType;
  /**
   * The limit of articles to get
   */
  limit?: number | undefined;
  cursor?: string | undefined;
  /**
   * The user ID to get articles for
   */
  userId?: string | undefined;
  /**
   * The categories to get articles for
   */
  categories?: Array<string> | undefined;
  /**
   * The languages to get articles for
   */
  languages?: Array<string> | undefined;
};

/** @internal */
export const ArticleGetArticlesPaginatedType$outboundSchema: z.ZodMiniEnum<
  typeof ArticleGetArticlesPaginatedType
> = z.enum(ArticleGetArticlesPaginatedType);

/** @internal */
export type ArticleGetArticlesPaginatedRequest$Outbound = {
  type: string;
  limit: number;
  cursor?: string | undefined;
  userId?: string | undefined;
  categories?: Array<string> | undefined;
  languages?: Array<string> | undefined;
};

/** @internal */
export const ArticleGetArticlesPaginatedRequest$outboundSchema: z.ZodMiniType<
  ArticleGetArticlesPaginatedRequest$Outbound,
  ArticleGetArticlesPaginatedRequest
> = z.object({
  type: ArticleGetArticlesPaginatedType$outboundSchema,
  limit: z._default(z.number(), 10),
  cursor: z.optional(z.string()),
  userId: z.optional(z.string()),
  categories: z.optional(z.array(z.string())),
  languages: z.optional(z.array(z.string())),
});

export function articleGetArticlesPaginatedRequestToJSON(
  articleGetArticlesPaginatedRequest: ArticleGetArticlesPaginatedRequest,
): string {
  return JSON.stringify(
    ArticleGetArticlesPaginatedRequest$outboundSchema.parse(
      articleGetArticlesPaginatedRequest,
    ),
  );
}
