/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ArticleGetArticleByIdRequest = {
  /**
   * The ID of the article to get
   */
  articleId: string;
};

/** @internal */
export type ArticleGetArticleByIdRequest$Outbound = {
  articleId: string;
};

/** @internal */
export const ArticleGetArticleByIdRequest$outboundSchema: z.ZodMiniType<
  ArticleGetArticleByIdRequest$Outbound,
  ArticleGetArticleByIdRequest
> = z.object({
  articleId: z.string(),
});

export function articleGetArticleByIdRequestToJSON(
  articleGetArticleByIdRequest: ArticleGetArticleByIdRequest,
): string {
  return JSON.stringify(
    ArticleGetArticleByIdRequest$outboundSchema.parse(
      articleGetArticleByIdRequest,
    ),
  );
}
