/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Type of ranking data to retrieve (damage, ground points, or money)
 */
export const DataType = {
  Damage: "damage",
  Points: "points",
  Money: "money",
} as const;
/**
 * Type of ranking data to retrieve (damage, ground points, or money)
 */
export type DataType = ClosedEnum<typeof DataType>;

/**
 * Whether to rank by user or country
 */
export const BattleRankingGetRankingType = {
  User: "user",
  Country: "country",
  Mu: "mu",
} as const;
/**
 * Whether to rank by user or country
 */
export type BattleRankingGetRankingType = ClosedEnum<
  typeof BattleRankingGetRankingType
>;

/**
 * Which side of the battle to rank
 */
export const Side = {
  Attacker: "attacker",
  Defender: "defender",
} as const;
/**
 * Which side of the battle to rank
 */
export type Side = ClosedEnum<typeof Side>;

export type BattleRankingGetRankingRequest = {
  /**
   * Optional battle ID to filter rankings
   */
  battleId?: string | undefined;
  /**
   * Optional round ID to filter rankings
   */
  roundId?: string | undefined;
  /**
   * Optional war ID to filter rankings
   */
  warId?: string | undefined;
  /**
   * Type of ranking data to retrieve (damage, ground points, or money)
   */
  dataType: DataType;
  /**
   * Whether to rank by user or country
   */
  type: BattleRankingGetRankingType;
  /**
   * Which side of the battle to rank
   */
  side: Side;
};

/** @internal */
export const DataType$inboundSchema: z.ZodMiniEnum<typeof DataType> = z.enum(
  DataType,
);
/** @internal */
export const DataType$outboundSchema: z.ZodMiniEnum<typeof DataType> =
  DataType$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataType$ {
  /** @deprecated use `DataType$inboundSchema` instead. */
  export const inboundSchema = DataType$inboundSchema;
  /** @deprecated use `DataType$outboundSchema` instead. */
  export const outboundSchema = DataType$outboundSchema;
}

/** @internal */
export const BattleRankingGetRankingType$inboundSchema: z.ZodMiniEnum<
  typeof BattleRankingGetRankingType
> = z.enum(BattleRankingGetRankingType);
/** @internal */
export const BattleRankingGetRankingType$outboundSchema: z.ZodMiniEnum<
  typeof BattleRankingGetRankingType
> = BattleRankingGetRankingType$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BattleRankingGetRankingType$ {
  /** @deprecated use `BattleRankingGetRankingType$inboundSchema` instead. */
  export const inboundSchema = BattleRankingGetRankingType$inboundSchema;
  /** @deprecated use `BattleRankingGetRankingType$outboundSchema` instead. */
  export const outboundSchema = BattleRankingGetRankingType$outboundSchema;
}

/** @internal */
export const Side$inboundSchema: z.ZodMiniEnum<typeof Side> = z.enum(Side);
/** @internal */
export const Side$outboundSchema: z.ZodMiniEnum<typeof Side> =
  Side$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Side$ {
  /** @deprecated use `Side$inboundSchema` instead. */
  export const inboundSchema = Side$inboundSchema;
  /** @deprecated use `Side$outboundSchema` instead. */
  export const outboundSchema = Side$outboundSchema;
}

/** @internal */
export const BattleRankingGetRankingRequest$inboundSchema: z.ZodMiniType<
  BattleRankingGetRankingRequest,
  unknown
> = z.object({
  battleId: types.optional(types.string()),
  roundId: types.optional(types.string()),
  warId: types.optional(types.string()),
  dataType: DataType$inboundSchema,
  type: BattleRankingGetRankingType$inboundSchema,
  side: Side$inboundSchema,
});
/** @internal */
export type BattleRankingGetRankingRequest$Outbound = {
  battleId?: string | undefined;
  roundId?: string | undefined;
  warId?: string | undefined;
  dataType: string;
  type: string;
  side: string;
};

/** @internal */
export const BattleRankingGetRankingRequest$outboundSchema: z.ZodMiniType<
  BattleRankingGetRankingRequest$Outbound,
  BattleRankingGetRankingRequest
> = z.object({
  battleId: z.optional(z.string()),
  roundId: z.optional(z.string()),
  warId: z.optional(z.string()),
  dataType: DataType$outboundSchema,
  type: BattleRankingGetRankingType$outboundSchema,
  side: Side$outboundSchema,
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BattleRankingGetRankingRequest$ {
  /** @deprecated use `BattleRankingGetRankingRequest$inboundSchema` instead. */
  export const inboundSchema = BattleRankingGetRankingRequest$inboundSchema;
  /** @deprecated use `BattleRankingGetRankingRequest$outboundSchema` instead. */
  export const outboundSchema = BattleRankingGetRankingRequest$outboundSchema;
  /** @deprecated use `BattleRankingGetRankingRequest$Outbound` instead. */
  export type Outbound = BattleRankingGetRankingRequest$Outbound;
}

export function battleRankingGetRankingRequestToJSON(
  battleRankingGetRankingRequest: BattleRankingGetRankingRequest,
): string {
  return JSON.stringify(
    BattleRankingGetRankingRequest$outboundSchema.parse(
      battleRankingGetRankingRequest,
    ),
  );
}
export function battleRankingGetRankingRequestFromJSON(
  jsonString: string,
): SafeParseResult<BattleRankingGetRankingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BattleRankingGetRankingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BattleRankingGetRankingRequest' from JSON`,
  );
}
