/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The direction to get the battles
 */
export const Direction = {
  Forward: "forward",
  Backward: "backward",
} as const;
/**
 * The direction to get the battles
 */
export type Direction = ClosedEnum<typeof Direction>;

/**
 * Filter type for battles
 */
export const Filter = {
  All: "all",
  YourCountry: "yourCountry",
  YourEnemies: "yourEnemies",
} as const;
/**
 * Filter type for battles
 */
export type Filter = ClosedEnum<typeof Filter>;

export type BattleGetBattlesRequest = {
  /**
   * Whether to get active battles
   */
  isActive?: boolean | undefined;
  /**
   * The limit of battles to get
   */
  limit?: number | undefined;
  /**
   * The cursor to get the next battles
   */
  cursor?: string | undefined;
  /**
   * The direction to get the battles
   */
  direction?: Direction | undefined;
  /**
   * Filter type for battles
   */
  filter?: Filter | undefined;
  /**
   * Filter battles by defender region ID
   */
  defenderRegionId?: string | undefined;
  /**
   * Filter battles by war ID
   */
  warId?: string | undefined;
  /**
   * Filter battles by country ID
   */
  countryId?: string | undefined;
};

/** @internal */
export const Direction$outboundSchema: z.ZodMiniEnum<typeof Direction> = z.enum(
  Direction,
);

/** @internal */
export const Filter$outboundSchema: z.ZodMiniEnum<typeof Filter> = z.enum(
  Filter,
);

/** @internal */
export type BattleGetBattlesRequest$Outbound = {
  isActive?: boolean | undefined;
  limit: number;
  cursor?: string | undefined;
  direction?: string | undefined;
  filter?: string | undefined;
  defenderRegionId?: string | undefined;
  warId?: string | undefined;
  countryId?: string | undefined;
};

/** @internal */
export const BattleGetBattlesRequest$outboundSchema: z.ZodMiniType<
  BattleGetBattlesRequest$Outbound,
  BattleGetBattlesRequest
> = z.object({
  isActive: z.optional(z.boolean()),
  limit: z._default(z.number(), 10),
  cursor: z.optional(z.string()),
  direction: z.optional(Direction$outboundSchema),
  filter: z.optional(Filter$outboundSchema),
  defenderRegionId: z.optional(z.string()),
  warId: z.optional(z.string()),
  countryId: z.optional(z.string()),
});

export function battleGetBattlesRequestToJSON(
  battleGetBattlesRequest: BattleGetBattlesRequest,
): string {
  return JSON.stringify(
    BattleGetBattlesRequest$outboundSchema.parse(battleGetBattlesRequest),
  );
}
