/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of ranking data to retrieve (damage, ground points, or money)
 */
export const DataType = {
  Damage: "damage",
  Points: "points",
  Money: "money",
} as const;
/**
 * Type of ranking data to retrieve (damage, ground points, or money)
 */
export type DataType = ClosedEnum<typeof DataType>;

/**
 * Whether to rank by user or country
 */
export const BattleRankingGetRankingType = {
  User: "user",
  Country: "country",
  Mu: "mu",
} as const;
/**
 * Whether to rank by user or country
 */
export type BattleRankingGetRankingType = ClosedEnum<
  typeof BattleRankingGetRankingType
>;

/**
 * Which side of the battle to rank
 */
export const Side = {
  Attacker: "attacker",
  Defender: "defender",
} as const;
/**
 * Which side of the battle to rank
 */
export type Side = ClosedEnum<typeof Side>;

export type BattleRankingGetRankingRequest = {
  /**
   * Optional battle ID to filter rankings
   */
  battleId?: string | undefined;
  /**
   * Optional round ID to filter rankings
   */
  roundId?: string | undefined;
  /**
   * Optional war ID to filter rankings
   */
  warId?: string | undefined;
  /**
   * Type of ranking data to retrieve (damage, ground points, or money)
   */
  dataType: DataType;
  /**
   * Whether to rank by user or country
   */
  type: BattleRankingGetRankingType;
  /**
   * Which side of the battle to rank
   */
  side: Side;
};

/** @internal */
export const DataType$outboundSchema: z.ZodMiniEnum<typeof DataType> = z.enum(
  DataType,
);

/** @internal */
export const BattleRankingGetRankingType$outboundSchema: z.ZodMiniEnum<
  typeof BattleRankingGetRankingType
> = z.enum(BattleRankingGetRankingType);

/** @internal */
export const Side$outboundSchema: z.ZodMiniEnum<typeof Side> = z.enum(Side);

/** @internal */
export type BattleRankingGetRankingRequest$Outbound = {
  battleId?: string | undefined;
  roundId?: string | undefined;
  warId?: string | undefined;
  dataType: string;
  type: string;
  side: string;
};

/** @internal */
export const BattleRankingGetRankingRequest$outboundSchema: z.ZodMiniType<
  BattleRankingGetRankingRequest$Outbound,
  BattleRankingGetRankingRequest
> = z.object({
  battleId: z.optional(z.string()),
  roundId: z.optional(z.string()),
  warId: z.optional(z.string()),
  dataType: DataType$outboundSchema,
  type: BattleRankingGetRankingType$outboundSchema,
  side: Side$outboundSchema,
});

export function battleRankingGetRankingRequestToJSON(
  battleRankingGetRankingRequest: BattleRankingGetRankingRequest,
): string {
  return JSON.stringify(
    BattleRankingGetRankingRequest$outboundSchema.parse(
      battleRankingGetRankingRequest,
    ),
  );
}
