/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type BattleGetByIdRequest = {
  /**
   * The unique identifier of the battle
   */
  battleId: string;
};

/** @internal */
export type BattleGetByIdRequest$Outbound = {
  battleId: string;
};

/** @internal */
export const BattleGetByIdRequest$outboundSchema: z.ZodMiniType<
  BattleGetByIdRequest$Outbound,
  BattleGetByIdRequest
> = z.object({
  battleId: z.string(),
});

export function battleGetByIdRequestToJSON(
  battleGetByIdRequest: BattleGetByIdRequest,
): string {
  return JSON.stringify(
    BattleGetByIdRequest$outboundSchema.parse(battleGetByIdRequest),
  );
}
