/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BattleGetByIdInput = {
  /**
   * The unique identifier of the battle
   */
  battleId: string;
};

export type BattleGetByIdRequest = {
  /**
   * JSON-encoded input parameters
   */
  input: BattleGetByIdInput;
};

/** @internal */
export const BattleGetByIdInput$inboundSchema: z.ZodMiniType<
  BattleGetByIdInput,
  unknown
> = z.object({
  battleId: types.string(),
});
/** @internal */
export type BattleGetByIdInput$Outbound = {
  battleId: string;
};

/** @internal */
export const BattleGetByIdInput$outboundSchema: z.ZodMiniType<
  BattleGetByIdInput$Outbound,
  BattleGetByIdInput
> = z.object({
  battleId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BattleGetByIdInput$ {
  /** @deprecated use `BattleGetByIdInput$inboundSchema` instead. */
  export const inboundSchema = BattleGetByIdInput$inboundSchema;
  /** @deprecated use `BattleGetByIdInput$outboundSchema` instead. */
  export const outboundSchema = BattleGetByIdInput$outboundSchema;
  /** @deprecated use `BattleGetByIdInput$Outbound` instead. */
  export type Outbound = BattleGetByIdInput$Outbound;
}

export function battleGetByIdInputToJSON(
  battleGetByIdInput: BattleGetByIdInput,
): string {
  return JSON.stringify(
    BattleGetByIdInput$outboundSchema.parse(battleGetByIdInput),
  );
}
export function battleGetByIdInputFromJSON(
  jsonString: string,
): SafeParseResult<BattleGetByIdInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BattleGetByIdInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BattleGetByIdInput' from JSON`,
  );
}

/** @internal */
export const BattleGetByIdRequest$inboundSchema: z.ZodMiniType<
  BattleGetByIdRequest,
  unknown
> = z.object({
  input: z.lazy(() => BattleGetByIdInput$inboundSchema),
});
/** @internal */
export type BattleGetByIdRequest$Outbound = {
  input: BattleGetByIdInput$Outbound;
};

/** @internal */
export const BattleGetByIdRequest$outboundSchema: z.ZodMiniType<
  BattleGetByIdRequest$Outbound,
  BattleGetByIdRequest
> = z.object({
  input: z.lazy(() => BattleGetByIdInput$outboundSchema),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BattleGetByIdRequest$ {
  /** @deprecated use `BattleGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = BattleGetByIdRequest$inboundSchema;
  /** @deprecated use `BattleGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = BattleGetByIdRequest$outboundSchema;
  /** @deprecated use `BattleGetByIdRequest$Outbound` instead. */
  export type Outbound = BattleGetByIdRequest$Outbound;
}

export function battleGetByIdRequestToJSON(
  battleGetByIdRequest: BattleGetByIdRequest,
): string {
  return JSON.stringify(
    BattleGetByIdRequest$outboundSchema.parse(battleGetByIdRequest),
  );
}
export function battleGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<BattleGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BattleGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BattleGetByIdRequest' from JSON`,
  );
}
