/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BattleGetLiveBattleDataRequest = {
  /**
   * The unique identifier of the battle
   */
  battleId: string;
  /**
   * Optional specific round number to retrieve
   */
  roundNumber?: number | undefined;
};

/** @internal */
export const BattleGetLiveBattleDataRequest$inboundSchema: z.ZodMiniType<
  BattleGetLiveBattleDataRequest,
  unknown
> = z.object({
  battleId: types.string(),
  roundNumber: types.optional(types.number()),
});
/** @internal */
export type BattleGetLiveBattleDataRequest$Outbound = {
  battleId: string;
  roundNumber?: number | undefined;
};

/** @internal */
export const BattleGetLiveBattleDataRequest$outboundSchema: z.ZodMiniType<
  BattleGetLiveBattleDataRequest$Outbound,
  BattleGetLiveBattleDataRequest
> = z.object({
  battleId: z.string(),
  roundNumber: z.optional(z.number()),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BattleGetLiveBattleDataRequest$ {
  /** @deprecated use `BattleGetLiveBattleDataRequest$inboundSchema` instead. */
  export const inboundSchema = BattleGetLiveBattleDataRequest$inboundSchema;
  /** @deprecated use `BattleGetLiveBattleDataRequest$outboundSchema` instead. */
  export const outboundSchema = BattleGetLiveBattleDataRequest$outboundSchema;
  /** @deprecated use `BattleGetLiveBattleDataRequest$Outbound` instead. */
  export type Outbound = BattleGetLiveBattleDataRequest$Outbound;
}

export function battleGetLiveBattleDataRequestToJSON(
  battleGetLiveBattleDataRequest: BattleGetLiveBattleDataRequest,
): string {
  return JSON.stringify(
    BattleGetLiveBattleDataRequest$outboundSchema.parse(
      battleGetLiveBattleDataRequest,
    ),
  );
}
export function battleGetLiveBattleDataRequestFromJSON(
  jsonString: string,
): SafeParseResult<BattleGetLiveBattleDataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BattleGetLiveBattleDataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BattleGetLiveBattleDataRequest' from JSON`,
  );
}
