/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type BattleGetLiveBattleDataRequest = {
  /**
   * The unique identifier of the battle
   */
  battleId: string;
  /**
   * Optional specific round number to retrieve
   */
  roundNumber?: number | undefined;
};

/** @internal */
export type BattleGetLiveBattleDataRequest$Outbound = {
  battleId: string;
  roundNumber?: number | undefined;
};

/** @internal */
export const BattleGetLiveBattleDataRequest$outboundSchema: z.ZodMiniType<
  BattleGetLiveBattleDataRequest$Outbound,
  BattleGetLiveBattleDataRequest
> = z.object({
  battleId: z.string(),
  roundNumber: z.optional(z.number()),
});

export function battleGetLiveBattleDataRequestToJSON(
  battleGetLiveBattleDataRequest: BattleGetLiveBattleDataRequest,
): string {
  return JSON.stringify(
    BattleGetLiveBattleDataRequest$outboundSchema.parse(
      battleGetLiveBattleDataRequest,
    ),
  );
}
