/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CompanyGetCompaniesRequest = {
  /**
   * Filter companies by user ID
   */
  userId?: string | undefined;
  /**
   * Filter companies by organization ID
   */
  orgId?: string | undefined;
  /**
   * Number of companies per page (1-100)
   */
  perPage?: number | undefined;
  /**
   * Pagination cursor for next page
   */
  cursor?: string | undefined;
};

/** @internal */
export type CompanyGetCompaniesRequest$Outbound = {
  userId?: string | undefined;
  orgId?: string | undefined;
  perPage: number;
  cursor?: string | undefined;
};

/** @internal */
export const CompanyGetCompaniesRequest$outboundSchema: z.ZodMiniType<
  CompanyGetCompaniesRequest$Outbound,
  CompanyGetCompaniesRequest
> = z.object({
  userId: z.optional(z.string()),
  orgId: z.optional(z.string()),
  perPage: z._default(z.number(), 10),
  cursor: z.optional(z.string()),
});

export function companyGetCompaniesRequestToJSON(
  companyGetCompaniesRequest: CompanyGetCompaniesRequest,
): string {
  return JSON.stringify(
    CompanyGetCompaniesRequest$outboundSchema.parse(companyGetCompaniesRequest),
  );
}
