/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CompanyGetByIdRequest = {
  /**
   * The unique identifier of the company
   */
  companyId: string;
};

/** @internal */
export type CompanyGetByIdRequest$Outbound = {
  companyId: string;
};

/** @internal */
export const CompanyGetByIdRequest$outboundSchema: z.ZodMiniType<
  CompanyGetByIdRequest$Outbound,
  CompanyGetByIdRequest
> = z.object({
  companyId: z.string(),
});

export function companyGetByIdRequestToJSON(
  companyGetByIdRequest: CompanyGetByIdRequest,
): string {
  return JSON.stringify(
    CompanyGetByIdRequest$outboundSchema.parse(companyGetByIdRequest),
  );
}
