/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CountryGetCountryByIdInput = {
  /**
   * The unique identifier of the country
   */
  countryId: string;
};

export type CountryGetCountryByIdRequest = {
  /**
   * JSON-encoded input parameters
   */
  input: CountryGetCountryByIdInput;
};

/** @internal */
export const CountryGetCountryByIdInput$inboundSchema: z.ZodMiniType<
  CountryGetCountryByIdInput,
  unknown
> = z.object({
  countryId: types.string(),
});
/** @internal */
export type CountryGetCountryByIdInput$Outbound = {
  countryId: string;
};

/** @internal */
export const CountryGetCountryByIdInput$outboundSchema: z.ZodMiniType<
  CountryGetCountryByIdInput$Outbound,
  CountryGetCountryByIdInput
> = z.object({
  countryId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CountryGetCountryByIdInput$ {
  /** @deprecated use `CountryGetCountryByIdInput$inboundSchema` instead. */
  export const inboundSchema = CountryGetCountryByIdInput$inboundSchema;
  /** @deprecated use `CountryGetCountryByIdInput$outboundSchema` instead. */
  export const outboundSchema = CountryGetCountryByIdInput$outboundSchema;
  /** @deprecated use `CountryGetCountryByIdInput$Outbound` instead. */
  export type Outbound = CountryGetCountryByIdInput$Outbound;
}

export function countryGetCountryByIdInputToJSON(
  countryGetCountryByIdInput: CountryGetCountryByIdInput,
): string {
  return JSON.stringify(
    CountryGetCountryByIdInput$outboundSchema.parse(countryGetCountryByIdInput),
  );
}
export function countryGetCountryByIdInputFromJSON(
  jsonString: string,
): SafeParseResult<CountryGetCountryByIdInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CountryGetCountryByIdInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CountryGetCountryByIdInput' from JSON`,
  );
}

/** @internal */
export const CountryGetCountryByIdRequest$inboundSchema: z.ZodMiniType<
  CountryGetCountryByIdRequest,
  unknown
> = z.object({
  input: z.lazy(() => CountryGetCountryByIdInput$inboundSchema),
});
/** @internal */
export type CountryGetCountryByIdRequest$Outbound = {
  input: CountryGetCountryByIdInput$Outbound;
};

/** @internal */
export const CountryGetCountryByIdRequest$outboundSchema: z.ZodMiniType<
  CountryGetCountryByIdRequest$Outbound,
  CountryGetCountryByIdRequest
> = z.object({
  input: z.lazy(() => CountryGetCountryByIdInput$outboundSchema),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CountryGetCountryByIdRequest$ {
  /** @deprecated use `CountryGetCountryByIdRequest$inboundSchema` instead. */
  export const inboundSchema = CountryGetCountryByIdRequest$inboundSchema;
  /** @deprecated use `CountryGetCountryByIdRequest$outboundSchema` instead. */
  export const outboundSchema = CountryGetCountryByIdRequest$outboundSchema;
  /** @deprecated use `CountryGetCountryByIdRequest$Outbound` instead. */
  export type Outbound = CountryGetCountryByIdRequest$Outbound;
}

export function countryGetCountryByIdRequestToJSON(
  countryGetCountryByIdRequest: CountryGetCountryByIdRequest,
): string {
  return JSON.stringify(
    CountryGetCountryByIdRequest$outboundSchema.parse(
      countryGetCountryByIdRequest,
    ),
  );
}
export function countryGetCountryByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<CountryGetCountryByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CountryGetCountryByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CountryGetCountryByIdRequest' from JSON`,
  );
}
