/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CountryGetCountryByIdRequest = {
  /**
   * The unique identifier of the country
   */
  countryId: string;
};

/** @internal */
export const CountryGetCountryByIdRequest$inboundSchema: z.ZodMiniType<
  CountryGetCountryByIdRequest,
  unknown
> = z.object({
  countryId: types.string(),
});
/** @internal */
export type CountryGetCountryByIdRequest$Outbound = {
  countryId: string;
};

/** @internal */
export const CountryGetCountryByIdRequest$outboundSchema: z.ZodMiniType<
  CountryGetCountryByIdRequest$Outbound,
  CountryGetCountryByIdRequest
> = z.object({
  countryId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CountryGetCountryByIdRequest$ {
  /** @deprecated use `CountryGetCountryByIdRequest$inboundSchema` instead. */
  export const inboundSchema = CountryGetCountryByIdRequest$inboundSchema;
  /** @deprecated use `CountryGetCountryByIdRequest$outboundSchema` instead. */
  export const outboundSchema = CountryGetCountryByIdRequest$outboundSchema;
  /** @deprecated use `CountryGetCountryByIdRequest$Outbound` instead. */
  export type Outbound = CountryGetCountryByIdRequest$Outbound;
}

export function countryGetCountryByIdRequestToJSON(
  countryGetCountryByIdRequest: CountryGetCountryByIdRequest,
): string {
  return JSON.stringify(
    CountryGetCountryByIdRequest$outboundSchema.parse(
      countryGetCountryByIdRequest,
    ),
  );
}
export function countryGetCountryByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<CountryGetCountryByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CountryGetCountryByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CountryGetCountryByIdRequest' from JSON`,
  );
}
