/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CountryGetCountryByIdRequest = {
  /**
   * The unique identifier of the country
   */
  countryId: string;
};

/** @internal */
export type CountryGetCountryByIdRequest$Outbound = {
  countryId: string;
};

/** @internal */
export const CountryGetCountryByIdRequest$outboundSchema: z.ZodMiniType<
  CountryGetCountryByIdRequest$Outbound,
  CountryGetCountryByIdRequest
> = z.object({
  countryId: z.string(),
});

export function countryGetCountryByIdRequestToJSON(
  countryGetCountryByIdRequest: CountryGetCountryByIdRequest,
): string {
  return JSON.stringify(
    CountryGetCountryByIdRequest$outboundSchema.parse(
      countryGetCountryByIdRequest,
    ),
  );
}
