/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CountryGetAllCountriesRequest = {};

/** @internal */
export type CountryGetAllCountriesRequest$Outbound = {};

/** @internal */
export const CountryGetAllCountriesRequest$outboundSchema: z.ZodMiniType<
  CountryGetAllCountriesRequest$Outbound,
  CountryGetAllCountriesRequest
> = z.object({});

export function countryGetAllCountriesRequestToJSON(
  countryGetAllCountriesRequest: CountryGetAllCountriesRequest,
): string {
  return JSON.stringify(
    CountryGetAllCountriesRequest$outboundSchema.parse(
      countryGetAllCountriesRequest,
    ),
  );
}
