/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type EventGetEventsPaginatedRequest = {
  /**
   * The limit of events to get
   */
  limit?: number | undefined;
  /**
   * The cursor to get the next events
   */
  cursor?: string | undefined;
  /**
   * Filter events by country ID
   */
  countryId?: string | undefined;
};

/** @internal */
export type EventGetEventsPaginatedRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
  countryId?: string | undefined;
};

/** @internal */
export const EventGetEventsPaginatedRequest$outboundSchema: z.ZodMiniType<
  EventGetEventsPaginatedRequest$Outbound,
  EventGetEventsPaginatedRequest
> = z.object({
  limit: z._default(z.number(), 10),
  cursor: z.optional(z.string()),
  countryId: z.optional(z.string()),
});

export function eventGetEventsPaginatedRequestToJSON(
  eventGetEventsPaginatedRequest: EventGetEventsPaginatedRequest,
): string {
  return JSON.stringify(
    EventGetEventsPaginatedRequest$outboundSchema.parse(
      eventGetEventsPaginatedRequest,
    ),
  );
}
