/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GameConfigGetGameConfigRequest = {};

/** @internal */
export type GameConfigGetGameConfigRequest$Outbound = {};

/** @internal */
export const GameConfigGetGameConfigRequest$outboundSchema: z.ZodMiniType<
  GameConfigGetGameConfigRequest$Outbound,
  GameConfigGetGameConfigRequest
> = z.object({});

export function gameConfigGetGameConfigRequestToJSON(
  gameConfigGetGameConfigRequest: GameConfigGetGameConfigRequest,
): string {
  return JSON.stringify(
    GameConfigGetGameConfigRequest$outboundSchema.parse(
      gameConfigGetGameConfigRequest,
    ),
  );
}
