/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GameConfigGetDatesRequest = {};

/** @internal */
export type GameConfigGetDatesRequest$Outbound = {};

/** @internal */
export const GameConfigGetDatesRequest$outboundSchema: z.ZodMiniType<
  GameConfigGetDatesRequest$Outbound,
  GameConfigGetDatesRequest
> = z.object({});

export function gameConfigGetDatesRequestToJSON(
  gameConfigGetDatesRequest: GameConfigGetDatesRequest,
): string {
  return JSON.stringify(
    GameConfigGetDatesRequest$outboundSchema.parse(gameConfigGetDatesRequest),
  );
}
