/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GovernmentGetByCountryIdRequest = {
  /**
   * The unique identifier of the country
   */
  countryId: string;
};

/** @internal */
export const GovernmentGetByCountryIdRequest$inboundSchema: z.ZodMiniType<
  GovernmentGetByCountryIdRequest,
  unknown
> = z.object({
  countryId: types.string(),
});
/** @internal */
export type GovernmentGetByCountryIdRequest$Outbound = {
  countryId: string;
};

/** @internal */
export const GovernmentGetByCountryIdRequest$outboundSchema: z.ZodMiniType<
  GovernmentGetByCountryIdRequest$Outbound,
  GovernmentGetByCountryIdRequest
> = z.object({
  countryId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GovernmentGetByCountryIdRequest$ {
  /** @deprecated use `GovernmentGetByCountryIdRequest$inboundSchema` instead. */
  export const inboundSchema = GovernmentGetByCountryIdRequest$inboundSchema;
  /** @deprecated use `GovernmentGetByCountryIdRequest$outboundSchema` instead. */
  export const outboundSchema = GovernmentGetByCountryIdRequest$outboundSchema;
  /** @deprecated use `GovernmentGetByCountryIdRequest$Outbound` instead. */
  export type Outbound = GovernmentGetByCountryIdRequest$Outbound;
}

export function governmentGetByCountryIdRequestToJSON(
  governmentGetByCountryIdRequest: GovernmentGetByCountryIdRequest,
): string {
  return JSON.stringify(
    GovernmentGetByCountryIdRequest$outboundSchema.parse(
      governmentGetByCountryIdRequest,
    ),
  );
}
export function governmentGetByCountryIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GovernmentGetByCountryIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GovernmentGetByCountryIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GovernmentGetByCountryIdRequest' from JSON`,
  );
}
