/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GovernmentGetByCountryIdRequest = {
  /**
   * The unique identifier of the country
   */
  countryId: string;
};

/** @internal */
export type GovernmentGetByCountryIdRequest$Outbound = {
  countryId: string;
};

/** @internal */
export const GovernmentGetByCountryIdRequest$outboundSchema: z.ZodMiniType<
  GovernmentGetByCountryIdRequest$Outbound,
  GovernmentGetByCountryIdRequest
> = z.object({
  countryId: z.string(),
});

export function governmentGetByCountryIdRequestToJSON(
  governmentGetByCountryIdRequest: GovernmentGetByCountryIdRequest,
): string {
  return JSON.stringify(
    GovernmentGetByCountryIdRequest$outboundSchema.parse(
      governmentGetByCountryIdRequest,
    ),
  );
}
