/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ItemTradingGetPricesRequest = {};

/** @internal */
export type ItemTradingGetPricesRequest$Outbound = {};

/** @internal */
export const ItemTradingGetPricesRequest$outboundSchema: z.ZodMiniType<
  ItemTradingGetPricesRequest$Outbound,
  ItemTradingGetPricesRequest
> = z.object({});

export function itemTradingGetPricesRequestToJSON(
  itemTradingGetPricesRequest: ItemTradingGetPricesRequest,
): string {
  return JSON.stringify(
    ItemTradingGetPricesRequest$outboundSchema.parse(
      itemTradingGetPricesRequest,
    ),
  );
}
