/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ItemOfferGetByIdRequest = {
  itemOfferId: string;
};

/** @internal */
export type ItemOfferGetByIdRequest$Outbound = {
  itemOfferId: string;
};

/** @internal */
export const ItemOfferGetByIdRequest$outboundSchema: z.ZodMiniType<
  ItemOfferGetByIdRequest$Outbound,
  ItemOfferGetByIdRequest
> = z.object({
  itemOfferId: z.string(),
});

export function itemOfferGetByIdRequestToJSON(
  itemOfferGetByIdRequest: ItemOfferGetByIdRequest,
): string {
  return JSON.stringify(
    ItemOfferGetByIdRequest$outboundSchema.parse(itemOfferGetByIdRequest),
  );
}
