/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MuGetByIdRequest = {
  muId: string;
};

/** @internal */
export type MuGetByIdRequest$Outbound = {
  muId: string;
};

/** @internal */
export const MuGetByIdRequest$outboundSchema: z.ZodMiniType<
  MuGetByIdRequest$Outbound,
  MuGetByIdRequest
> = z.object({
  muId: z.string(),
});

export function muGetByIdRequestToJSON(
  muGetByIdRequest: MuGetByIdRequest,
): string {
  return JSON.stringify(
    MuGetByIdRequest$outboundSchema.parse(muGetByIdRequest),
  );
}
