/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MuGetManyPaginatedRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  memberId?: string | undefined;
  userId?: string | undefined;
  orgId?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export type MuGetManyPaginatedRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
  memberId?: string | undefined;
  userId?: string | undefined;
  orgId?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const MuGetManyPaginatedRequest$outboundSchema: z.ZodMiniType<
  MuGetManyPaginatedRequest$Outbound,
  MuGetManyPaginatedRequest
> = z.object({
  limit: z._default(z.number(), 20),
  cursor: z.optional(z.string()),
  memberId: z.optional(z.string()),
  userId: z.optional(z.string()),
  orgId: z.optional(z.string()),
  search: z.optional(z.string()),
});

export function muGetManyPaginatedRequestToJSON(
  muGetManyPaginatedRequest: MuGetManyPaginatedRequest,
): string {
  return JSON.stringify(
    MuGetManyPaginatedRequest$outboundSchema.parse(muGetManyPaginatedRequest),
  );
}
