/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of ranking to retrieve
 */
export const RankingType = {
  WeeklyCountryDamages: "weeklyCountryDamages",
  WeeklyCountryDamagesPerCitizen: "weeklyCountryDamagesPerCitizen",
  CountryRegionDiff: "countryRegionDiff",
  CountryDevelopment: "countryDevelopment",
  CountryActivePopulation: "countryActivePopulation",
  CountryDamages: "countryDamages",
  CountryWealth: "countryWealth",
  CountryProductionBonus: "countryProductionBonus",
  CountryBounty: "countryBounty",
  WeeklyUserDamages: "weeklyUserDamages",
  UserDamages: "userDamages",
  UserWealth: "userWealth",
  UserLevel: "userLevel",
  UserReferrals: "userReferrals",
  UserSubscribers: "userSubscribers",
  UserTerrain: "userTerrain",
  UserPremiumMonths: "userPremiumMonths",
  UserPremiumGifts: "userPremiumGifts",
  UserCasesOpened: "userCasesOpened",
  UserGemsPurchased: "userGemsPurchased",
  UserBounty: "userBounty",
  MuWeeklyDamages: "muWeeklyDamages",
  MuDamages: "muDamages",
  MuTerrain: "muTerrain",
  MuWealth: "muWealth",
  MuBounty: "muBounty",
} as const;
/**
 * The type of ranking to retrieve
 */
export type RankingType = ClosedEnum<typeof RankingType>;

export type RankingGetRankingRequest = {
  /**
   * The type of ranking to retrieve
   */
  rankingType: RankingType;
};

/** @internal */
export const RankingType$outboundSchema: z.ZodMiniEnum<typeof RankingType> = z
  .enum(RankingType);

/** @internal */
export type RankingGetRankingRequest$Outbound = {
  rankingType: string;
};

/** @internal */
export const RankingGetRankingRequest$outboundSchema: z.ZodMiniType<
  RankingGetRankingRequest$Outbound,
  RankingGetRankingRequest
> = z.object({
  rankingType: RankingType$outboundSchema,
});

export function rankingGetRankingRequestToJSON(
  rankingGetRankingRequest: RankingGetRankingRequest,
): string {
  return JSON.stringify(
    RankingGetRankingRequest$outboundSchema.parse(rankingGetRankingRequest),
  );
}
