/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RegionGetByIdRequest = {
  /**
   * The unique identifier of the region
   */
  regionId: string;
};

/** @internal */
export type RegionGetByIdRequest$Outbound = {
  regionId: string;
};

/** @internal */
export const RegionGetByIdRequest$outboundSchema: z.ZodMiniType<
  RegionGetByIdRequest$Outbound,
  RegionGetByIdRequest
> = z.object({
  regionId: z.string(),
});

export function regionGetByIdRequestToJSON(
  regionGetByIdRequest: RegionGetByIdRequest,
): string {
  return JSON.stringify(
    RegionGetByIdRequest$outboundSchema.parse(regionGetByIdRequest),
  );
}
