/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RegionGetRegionsObjectInput = {};

export type RegionGetRegionsObjectRequest = {
  /**
   * JSON-encoded input parameters
   */
  input?: RegionGetRegionsObjectInput | undefined;
};

/** @internal */
export const RegionGetRegionsObjectInput$inboundSchema: z.ZodMiniType<
  RegionGetRegionsObjectInput,
  unknown
> = z.object({});
/** @internal */
export type RegionGetRegionsObjectInput$Outbound = {};

/** @internal */
export const RegionGetRegionsObjectInput$outboundSchema: z.ZodMiniType<
  RegionGetRegionsObjectInput$Outbound,
  RegionGetRegionsObjectInput
> = z.object({});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RegionGetRegionsObjectInput$ {
  /** @deprecated use `RegionGetRegionsObjectInput$inboundSchema` instead. */
  export const inboundSchema = RegionGetRegionsObjectInput$inboundSchema;
  /** @deprecated use `RegionGetRegionsObjectInput$outboundSchema` instead. */
  export const outboundSchema = RegionGetRegionsObjectInput$outboundSchema;
  /** @deprecated use `RegionGetRegionsObjectInput$Outbound` instead. */
  export type Outbound = RegionGetRegionsObjectInput$Outbound;
}

export function regionGetRegionsObjectInputToJSON(
  regionGetRegionsObjectInput: RegionGetRegionsObjectInput,
): string {
  return JSON.stringify(
    RegionGetRegionsObjectInput$outboundSchema.parse(
      regionGetRegionsObjectInput,
    ),
  );
}
export function regionGetRegionsObjectInputFromJSON(
  jsonString: string,
): SafeParseResult<RegionGetRegionsObjectInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegionGetRegionsObjectInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegionGetRegionsObjectInput' from JSON`,
  );
}

/** @internal */
export const RegionGetRegionsObjectRequest$inboundSchema: z.ZodMiniType<
  RegionGetRegionsObjectRequest,
  unknown
> = z.object({
  input: types.optional(
    z.lazy(() => RegionGetRegionsObjectInput$inboundSchema),
  ),
});
/** @internal */
export type RegionGetRegionsObjectRequest$Outbound = {
  input?: RegionGetRegionsObjectInput$Outbound | undefined;
};

/** @internal */
export const RegionGetRegionsObjectRequest$outboundSchema: z.ZodMiniType<
  RegionGetRegionsObjectRequest$Outbound,
  RegionGetRegionsObjectRequest
> = z.object({
  input: z.optional(z.lazy(() => RegionGetRegionsObjectInput$outboundSchema)),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RegionGetRegionsObjectRequest$ {
  /** @deprecated use `RegionGetRegionsObjectRequest$inboundSchema` instead. */
  export const inboundSchema = RegionGetRegionsObjectRequest$inboundSchema;
  /** @deprecated use `RegionGetRegionsObjectRequest$outboundSchema` instead. */
  export const outboundSchema = RegionGetRegionsObjectRequest$outboundSchema;
  /** @deprecated use `RegionGetRegionsObjectRequest$Outbound` instead. */
  export type Outbound = RegionGetRegionsObjectRequest$Outbound;
}

export function regionGetRegionsObjectRequestToJSON(
  regionGetRegionsObjectRequest: RegionGetRegionsObjectRequest,
): string {
  return JSON.stringify(
    RegionGetRegionsObjectRequest$outboundSchema.parse(
      regionGetRegionsObjectRequest,
    ),
  );
}
export function regionGetRegionsObjectRequestFromJSON(
  jsonString: string,
): SafeParseResult<RegionGetRegionsObjectRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegionGetRegionsObjectRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegionGetRegionsObjectRequest' from JSON`,
  );
}
