/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RegionGetRegionsObjectRequest = {};

/** @internal */
export type RegionGetRegionsObjectRequest$Outbound = {};

/** @internal */
export const RegionGetRegionsObjectRequest$outboundSchema: z.ZodMiniType<
  RegionGetRegionsObjectRequest$Outbound,
  RegionGetRegionsObjectRequest
> = z.object({});

export function regionGetRegionsObjectRequestToJSON(
  regionGetRegionsObjectRequest: RegionGetRegionsObjectRequest,
): string {
  return JSON.stringify(
    RegionGetRegionsObjectRequest$outboundSchema.parse(
      regionGetRegionsObjectRequest,
    ),
  );
}
