/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RoundGetByIdRequest = {
  /**
   * The unique identifier of the round
   */
  roundId: string;
};

/** @internal */
export const RoundGetByIdRequest$inboundSchema: z.ZodMiniType<
  RoundGetByIdRequest,
  unknown
> = z.object({
  roundId: types.string(),
});
/** @internal */
export type RoundGetByIdRequest$Outbound = {
  roundId: string;
};

/** @internal */
export const RoundGetByIdRequest$outboundSchema: z.ZodMiniType<
  RoundGetByIdRequest$Outbound,
  RoundGetByIdRequest
> = z.object({
  roundId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RoundGetByIdRequest$ {
  /** @deprecated use `RoundGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = RoundGetByIdRequest$inboundSchema;
  /** @deprecated use `RoundGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = RoundGetByIdRequest$outboundSchema;
  /** @deprecated use `RoundGetByIdRequest$Outbound` instead. */
  export type Outbound = RoundGetByIdRequest$Outbound;
}

export function roundGetByIdRequestToJSON(
  roundGetByIdRequest: RoundGetByIdRequest,
): string {
  return JSON.stringify(
    RoundGetByIdRequest$outboundSchema.parse(roundGetByIdRequest),
  );
}
export function roundGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<RoundGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoundGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoundGetByIdRequest' from JSON`,
  );
}
