/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RoundGetLastHitsRequest = {
  /**
   * The unique identifier of the round
   */
  roundId: string;
};

/** @internal */
export type RoundGetLastHitsRequest$Outbound = {
  roundId: string;
};

/** @internal */
export const RoundGetLastHitsRequest$outboundSchema: z.ZodMiniType<
  RoundGetLastHitsRequest$Outbound,
  RoundGetLastHitsRequest
> = z.object({
  roundId: z.string(),
});

export function roundGetLastHitsRequestToJSON(
  roundGetLastHitsRequest: RoundGetLastHitsRequest,
): string {
  return JSON.stringify(
    RoundGetLastHitsRequest$outboundSchema.parse(roundGetLastHitsRequest),
  );
}
