/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RoundGetByIdRequest = {
  /**
   * The unique identifier of the round
   */
  roundId: string;
};

/** @internal */
export type RoundGetByIdRequest$Outbound = {
  roundId: string;
};

/** @internal */
export const RoundGetByIdRequest$outboundSchema: z.ZodMiniType<
  RoundGetByIdRequest$Outbound,
  RoundGetByIdRequest
> = z.object({
  roundId: z.string(),
});

export function roundGetByIdRequestToJSON(
  roundGetByIdRequest: RoundGetByIdRequest,
): string {
  return JSON.stringify(
    RoundGetByIdRequest$outboundSchema.parse(roundGetByIdRequest),
  );
}
