/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SearchSearchAnythingRequest = {
  /**
   * The search query string
   */
  searchText: string;
};

/** @internal */
export type SearchSearchAnythingRequest$Outbound = {
  searchText: string;
};

/** @internal */
export const SearchSearchAnythingRequest$outboundSchema: z.ZodMiniType<
  SearchSearchAnythingRequest$Outbound,
  SearchSearchAnythingRequest
> = z.object({
  searchText: z.string(),
});

export function searchSearchAnythingRequestToJSON(
  searchSearchAnythingRequest: SearchSearchAnythingRequest,
): string {
  return JSON.stringify(
    SearchSearchAnythingRequest$outboundSchema.parse(
      searchSearchAnythingRequest,
    ),
  );
}
