/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TradingOrderGetTopOrdersRequest = {
  /**
   * The item code to get orders for
   */
  itemCode: string;
  /**
   * The limit of orders to get
   */
  limit?: number | undefined;
};

/** @internal */
export type TradingOrderGetTopOrdersRequest$Outbound = {
  itemCode: string;
  limit: number;
};

/** @internal */
export const TradingOrderGetTopOrdersRequest$outboundSchema: z.ZodMiniType<
  TradingOrderGetTopOrdersRequest$Outbound,
  TradingOrderGetTopOrdersRequest
> = z.object({
  itemCode: z.string(),
  limit: z._default(z.int(), 10),
});

export function tradingOrderGetTopOrdersRequestToJSON(
  tradingOrderGetTopOrdersRequest: TradingOrderGetTopOrdersRequest,
): string {
  return JSON.stringify(
    TradingOrderGetTopOrdersRequest$outboundSchema.parse(
      tradingOrderGetTopOrdersRequest,
    ),
  );
}
