/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";
import { smartUnion } from "../../types/smartUnion.js";

export const TransactionTypeEnum2 = {
  ApplicationFee: "applicationFee",
  Trading: "trading",
  ItemMarket: "itemMarket",
  Wage: "wage",
  Donation: "donation",
  ArticleTip: "articleTip",
  OpenCase: "openCase",
  CraftItem: "craftItem",
  DismantleItem: "dismantleItem",
} as const;
export type TransactionTypeEnum2 = ClosedEnum<typeof TransactionTypeEnum2>;

export const TransactionTypeEnum1 = {
  ApplicationFee: "applicationFee",
  Trading: "trading",
  ItemMarket: "itemMarket",
  Wage: "wage",
  Donation: "donation",
  ArticleTip: "articleTip",
  OpenCase: "openCase",
  CraftItem: "craftItem",
  DismantleItem: "dismantleItem",
} as const;
export type TransactionTypeEnum1 = ClosedEnum<typeof TransactionTypeEnum1>;

/**
 * The type of transactions to get
 */
export type TransactionType =
  | TransactionTypeEnum1
  | Array<TransactionTypeEnum2>;

export type TransactionGetPaginatedTransactionsRequest = {
  /**
   * The limit of transactions to get
   */
  limit?: number | undefined;
  /**
   * The cursor to get the next transactions
   */
  cursor?: string | undefined;
  /**
   * The user ID to get transactions for
   */
  userId?: string | undefined;
  /**
   * The MU ID to get transactions for
   */
  muId?: string | undefined;
  /**
   * The country ID to get transactions for
   */
  countryId?: string | undefined;
  /**
   * The item code to get transactions for
   */
  itemCode?: string | undefined;
  /**
   * The type of transactions to get
   */
  transactionType?:
    | TransactionTypeEnum1
    | Array<TransactionTypeEnum2>
    | undefined;
};

/** @internal */
export const TransactionTypeEnum2$outboundSchema: z.ZodMiniEnum<
  typeof TransactionTypeEnum2
> = z.enum(TransactionTypeEnum2);

/** @internal */
export const TransactionTypeEnum1$outboundSchema: z.ZodMiniEnum<
  typeof TransactionTypeEnum1
> = z.enum(TransactionTypeEnum1);

/** @internal */
export type TransactionType$Outbound = string | Array<string>;

/** @internal */
export const TransactionType$outboundSchema: z.ZodMiniType<
  TransactionType$Outbound,
  TransactionType
> = smartUnion([
  TransactionTypeEnum1$outboundSchema,
  z.array(TransactionTypeEnum2$outboundSchema),
]);

export function transactionTypeToJSON(
  transactionType: TransactionType,
): string {
  return JSON.stringify(TransactionType$outboundSchema.parse(transactionType));
}

/** @internal */
export type TransactionGetPaginatedTransactionsRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
  userId?: string | undefined;
  muId?: string | undefined;
  countryId?: string | undefined;
  itemCode?: string | undefined;
  transactionType?: string | Array<string> | undefined;
};

/** @internal */
export const TransactionGetPaginatedTransactionsRequest$outboundSchema:
  z.ZodMiniType<
    TransactionGetPaginatedTransactionsRequest$Outbound,
    TransactionGetPaginatedTransactionsRequest
  > = z.object({
    limit: z._default(z.int(), 10),
    cursor: z.optional(z.string()),
    userId: z.optional(z.string()),
    muId: z.optional(z.string()),
    countryId: z.optional(z.string()),
    itemCode: z.optional(z.string()),
    transactionType: z.optional(
      smartUnion([
        TransactionTypeEnum1$outboundSchema,
        z.array(TransactionTypeEnum2$outboundSchema),
      ]),
    ),
  });

export function transactionGetPaginatedTransactionsRequestToJSON(
  transactionGetPaginatedTransactionsRequest:
    TransactionGetPaginatedTransactionsRequest,
): string {
  return JSON.stringify(
    TransactionGetPaginatedTransactionsRequest$outboundSchema.parse(
      transactionGetPaginatedTransactionsRequest,
    ),
  );
}
