/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const TransactionTypeEnum2 = {
  ApplicationFee: "applicationFee",
  Trading: "trading",
  ItemMarket: "itemMarket",
  Wage: "wage",
  Donation: "donation",
  ArticleTip: "articleTip",
  OpenCase: "openCase",
  CraftItem: "craftItem",
  DismantleItem: "dismantleItem",
} as const;
export type TransactionTypeEnum2 = ClosedEnum<typeof TransactionTypeEnum2>;

export const TransactionTypeEnum1 = {
  ApplicationFee: "applicationFee",
  Trading: "trading",
  ItemMarket: "itemMarket",
  Wage: "wage",
  Donation: "donation",
  ArticleTip: "articleTip",
  OpenCase: "openCase",
  CraftItem: "craftItem",
  DismantleItem: "dismantleItem",
} as const;
export type TransactionTypeEnum1 = ClosedEnum<typeof TransactionTypeEnum1>;

/**
 * The type of transactions to get
 */
export type TransactionType =
  | TransactionTypeEnum1
  | Array<TransactionTypeEnum2>;

export type TransactionGetPaginatedTransactionsInput = {
  /**
   * The limit of transactions to get
   */
  limit?: number | undefined;
  /**
   * The cursor to get the next transactions
   */
  cursor?: string | undefined;
  /**
   * The user ID to get transactions for
   */
  userId?: string | undefined;
  /**
   * The MU ID to get transactions for
   */
  muId?: string | undefined;
  /**
   * The country ID to get transactions for
   */
  countryId?: string | undefined;
  /**
   * The item code to get transactions for
   */
  itemCode?: string | undefined;
  /**
   * The type of transactions to get
   */
  transactionType?:
    | TransactionTypeEnum1
    | Array<TransactionTypeEnum2>
    | undefined;
};

export type TransactionGetPaginatedTransactionsRequest = {
  /**
   * JSON-encoded input parameters
   */
  input?: TransactionGetPaginatedTransactionsInput | undefined;
};

/** @internal */
export const TransactionTypeEnum2$inboundSchema: z.ZodMiniEnum<
  typeof TransactionTypeEnum2
> = z.enum(TransactionTypeEnum2);
/** @internal */
export const TransactionTypeEnum2$outboundSchema: z.ZodMiniEnum<
  typeof TransactionTypeEnum2
> = TransactionTypeEnum2$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionTypeEnum2$ {
  /** @deprecated use `TransactionTypeEnum2$inboundSchema` instead. */
  export const inboundSchema = TransactionTypeEnum2$inboundSchema;
  /** @deprecated use `TransactionTypeEnum2$outboundSchema` instead. */
  export const outboundSchema = TransactionTypeEnum2$outboundSchema;
}

/** @internal */
export const TransactionTypeEnum1$inboundSchema: z.ZodMiniEnum<
  typeof TransactionTypeEnum1
> = z.enum(TransactionTypeEnum1);
/** @internal */
export const TransactionTypeEnum1$outboundSchema: z.ZodMiniEnum<
  typeof TransactionTypeEnum1
> = TransactionTypeEnum1$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionTypeEnum1$ {
  /** @deprecated use `TransactionTypeEnum1$inboundSchema` instead. */
  export const inboundSchema = TransactionTypeEnum1$inboundSchema;
  /** @deprecated use `TransactionTypeEnum1$outboundSchema` instead. */
  export const outboundSchema = TransactionTypeEnum1$outboundSchema;
}

/** @internal */
export const TransactionType$inboundSchema: z.ZodMiniType<
  TransactionType,
  unknown
> = smartUnion([
  TransactionTypeEnum1$inboundSchema,
  z.array(TransactionTypeEnum2$inboundSchema),
]);
/** @internal */
export type TransactionType$Outbound = string | Array<string>;

/** @internal */
export const TransactionType$outboundSchema: z.ZodMiniType<
  TransactionType$Outbound,
  TransactionType
> = smartUnion([
  TransactionTypeEnum1$outboundSchema,
  z.array(TransactionTypeEnum2$outboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionType$ {
  /** @deprecated use `TransactionType$inboundSchema` instead. */
  export const inboundSchema = TransactionType$inboundSchema;
  /** @deprecated use `TransactionType$outboundSchema` instead. */
  export const outboundSchema = TransactionType$outboundSchema;
  /** @deprecated use `TransactionType$Outbound` instead. */
  export type Outbound = TransactionType$Outbound;
}

export function transactionTypeToJSON(
  transactionType: TransactionType,
): string {
  return JSON.stringify(TransactionType$outboundSchema.parse(transactionType));
}
export function transactionTypeFromJSON(
  jsonString: string,
): SafeParseResult<TransactionType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionType' from JSON`,
  );
}

/** @internal */
export const TransactionGetPaginatedTransactionsInput$inboundSchema:
  z.ZodMiniType<TransactionGetPaginatedTransactionsInput, unknown> = z.object({
    limit: z._default(types.number(), 10),
    cursor: types.optional(types.string()),
    userId: types.optional(types.string()),
    muId: types.optional(types.string()),
    countryId: types.optional(types.string()),
    itemCode: types.optional(types.string()),
    transactionType: types.optional(
      smartUnion([
        TransactionTypeEnum1$inboundSchema,
        z.array(TransactionTypeEnum2$inboundSchema),
      ]),
    ),
  });
/** @internal */
export type TransactionGetPaginatedTransactionsInput$Outbound = {
  limit: number;
  cursor?: string | undefined;
  userId?: string | undefined;
  muId?: string | undefined;
  countryId?: string | undefined;
  itemCode?: string | undefined;
  transactionType?: string | Array<string> | undefined;
};

/** @internal */
export const TransactionGetPaginatedTransactionsInput$outboundSchema:
  z.ZodMiniType<
    TransactionGetPaginatedTransactionsInput$Outbound,
    TransactionGetPaginatedTransactionsInput
  > = z.object({
    limit: z._default(z.int(), 10),
    cursor: z.optional(z.string()),
    userId: z.optional(z.string()),
    muId: z.optional(z.string()),
    countryId: z.optional(z.string()),
    itemCode: z.optional(z.string()),
    transactionType: z.optional(
      smartUnion([
        TransactionTypeEnum1$outboundSchema,
        z.array(TransactionTypeEnum2$outboundSchema),
      ]),
    ),
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionGetPaginatedTransactionsInput$ {
  /** @deprecated use `TransactionGetPaginatedTransactionsInput$inboundSchema` instead. */
  export const inboundSchema =
    TransactionGetPaginatedTransactionsInput$inboundSchema;
  /** @deprecated use `TransactionGetPaginatedTransactionsInput$outboundSchema` instead. */
  export const outboundSchema =
    TransactionGetPaginatedTransactionsInput$outboundSchema;
  /** @deprecated use `TransactionGetPaginatedTransactionsInput$Outbound` instead. */
  export type Outbound = TransactionGetPaginatedTransactionsInput$Outbound;
}

export function transactionGetPaginatedTransactionsInputToJSON(
  transactionGetPaginatedTransactionsInput:
    TransactionGetPaginatedTransactionsInput,
): string {
  return JSON.stringify(
    TransactionGetPaginatedTransactionsInput$outboundSchema.parse(
      transactionGetPaginatedTransactionsInput,
    ),
  );
}
export function transactionGetPaginatedTransactionsInputFromJSON(
  jsonString: string,
): SafeParseResult<
  TransactionGetPaginatedTransactionsInput,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TransactionGetPaginatedTransactionsInput$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TransactionGetPaginatedTransactionsInput' from JSON`,
  );
}

/** @internal */
export const TransactionGetPaginatedTransactionsRequest$inboundSchema:
  z.ZodMiniType<TransactionGetPaginatedTransactionsRequest, unknown> = z.object(
    {
      input: types.optional(z.lazy(() =>
        TransactionGetPaginatedTransactionsInput$inboundSchema
      )),
    },
  );
/** @internal */
export type TransactionGetPaginatedTransactionsRequest$Outbound = {
  input?: TransactionGetPaginatedTransactionsInput$Outbound | undefined;
};

/** @internal */
export const TransactionGetPaginatedTransactionsRequest$outboundSchema:
  z.ZodMiniType<
    TransactionGetPaginatedTransactionsRequest$Outbound,
    TransactionGetPaginatedTransactionsRequest
  > = z.object({
    input: z.optional(
      z.lazy(() => TransactionGetPaginatedTransactionsInput$outboundSchema),
    ),
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionGetPaginatedTransactionsRequest$ {
  /** @deprecated use `TransactionGetPaginatedTransactionsRequest$inboundSchema` instead. */
  export const inboundSchema =
    TransactionGetPaginatedTransactionsRequest$inboundSchema;
  /** @deprecated use `TransactionGetPaginatedTransactionsRequest$outboundSchema` instead. */
  export const outboundSchema =
    TransactionGetPaginatedTransactionsRequest$outboundSchema;
  /** @deprecated use `TransactionGetPaginatedTransactionsRequest$Outbound` instead. */
  export type Outbound = TransactionGetPaginatedTransactionsRequest$Outbound;
}

export function transactionGetPaginatedTransactionsRequestToJSON(
  transactionGetPaginatedTransactionsRequest:
    TransactionGetPaginatedTransactionsRequest,
): string {
  return JSON.stringify(
    TransactionGetPaginatedTransactionsRequest$outboundSchema.parse(
      transactionGetPaginatedTransactionsRequest,
    ),
  );
}
export function transactionGetPaginatedTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  TransactionGetPaginatedTransactionsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TransactionGetPaginatedTransactionsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TransactionGetPaginatedTransactionsRequest' from JSON`,
  );
}
