/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The upgrade type to get
 */
export const UpgradeType = {
  Bunker: "bunker",
  Base: "base",
  Storage: "storage",
  AutomatedEngine: "automatedEngine",
  BreakRoom: "breakRoom",
  Headquarters: "headquarters",
  Dormitories: "dormitories",
} as const;
/**
 * The upgrade type to get
 */
export type UpgradeType = ClosedEnum<typeof UpgradeType>;

export type UpgradeGetUpgradeByTypeAndEntityRequest = {
  /**
   * The upgrade type to get
   */
  upgradeType: UpgradeType;
  /**
   * The region ID to get upgrade for
   */
  regionId?: string | undefined;
  /**
   * The company ID to get upgrade for
   */
  companyId?: string | undefined;
  /**
   * The military unit ID to get upgrade for
   */
  muId?: string | undefined;
};

/** @internal */
export const UpgradeType$outboundSchema: z.ZodMiniEnum<typeof UpgradeType> = z
  .enum(UpgradeType);

/** @internal */
export type UpgradeGetUpgradeByTypeAndEntityRequest$Outbound = {
  upgradeType: string;
  regionId?: string | undefined;
  companyId?: string | undefined;
  muId?: string | undefined;
};

/** @internal */
export const UpgradeGetUpgradeByTypeAndEntityRequest$outboundSchema:
  z.ZodMiniType<
    UpgradeGetUpgradeByTypeAndEntityRequest$Outbound,
    UpgradeGetUpgradeByTypeAndEntityRequest
  > = z.object({
    upgradeType: UpgradeType$outboundSchema,
    regionId: z.optional(z.string()),
    companyId: z.optional(z.string()),
    muId: z.optional(z.string()),
  });

export function upgradeGetUpgradeByTypeAndEntityRequestToJSON(
  upgradeGetUpgradeByTypeAndEntityRequest:
    UpgradeGetUpgradeByTypeAndEntityRequest,
): string {
  return JSON.stringify(
    UpgradeGetUpgradeByTypeAndEntityRequest$outboundSchema.parse(
      upgradeGetUpgradeByTypeAndEntityRequest,
    ),
  );
}
