/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UserGetUserLiteRequest = {
  /**
   * The unique identifier of the user
   */
  userId: string;
};

/** @internal */
export type UserGetUserLiteRequest$Outbound = {
  userId: string;
};

/** @internal */
export const UserGetUserLiteRequest$outboundSchema: z.ZodMiniType<
  UserGetUserLiteRequest$Outbound,
  UserGetUserLiteRequest
> = z.object({
  userId: z.string(),
});

export function userGetUserLiteRequestToJSON(
  userGetUserLiteRequest: UserGetUserLiteRequest,
): string {
  return JSON.stringify(
    UserGetUserLiteRequest$outboundSchema.parse(userGetUserLiteRequest),
  );
}
