/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserGetUserLiteInput = {
  /**
   * The unique identifier of the user
   */
  userId: string;
};

export type UserGetUserLiteRequest = {
  /**
   * JSON-encoded input parameters
   */
  input: UserGetUserLiteInput;
};

/** @internal */
export const UserGetUserLiteInput$inboundSchema: z.ZodMiniType<
  UserGetUserLiteInput,
  unknown
> = z.object({
  userId: types.string(),
});
/** @internal */
export type UserGetUserLiteInput$Outbound = {
  userId: string;
};

/** @internal */
export const UserGetUserLiteInput$outboundSchema: z.ZodMiniType<
  UserGetUserLiteInput$Outbound,
  UserGetUserLiteInput
> = z.object({
  userId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserGetUserLiteInput$ {
  /** @deprecated use `UserGetUserLiteInput$inboundSchema` instead. */
  export const inboundSchema = UserGetUserLiteInput$inboundSchema;
  /** @deprecated use `UserGetUserLiteInput$outboundSchema` instead. */
  export const outboundSchema = UserGetUserLiteInput$outboundSchema;
  /** @deprecated use `UserGetUserLiteInput$Outbound` instead. */
  export type Outbound = UserGetUserLiteInput$Outbound;
}

export function userGetUserLiteInputToJSON(
  userGetUserLiteInput: UserGetUserLiteInput,
): string {
  return JSON.stringify(
    UserGetUserLiteInput$outboundSchema.parse(userGetUserLiteInput),
  );
}
export function userGetUserLiteInputFromJSON(
  jsonString: string,
): SafeParseResult<UserGetUserLiteInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGetUserLiteInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGetUserLiteInput' from JSON`,
  );
}

/** @internal */
export const UserGetUserLiteRequest$inboundSchema: z.ZodMiniType<
  UserGetUserLiteRequest,
  unknown
> = z.object({
  input: z.lazy(() => UserGetUserLiteInput$inboundSchema),
});
/** @internal */
export type UserGetUserLiteRequest$Outbound = {
  input: UserGetUserLiteInput$Outbound;
};

/** @internal */
export const UserGetUserLiteRequest$outboundSchema: z.ZodMiniType<
  UserGetUserLiteRequest$Outbound,
  UserGetUserLiteRequest
> = z.object({
  input: z.lazy(() => UserGetUserLiteInput$outboundSchema),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserGetUserLiteRequest$ {
  /** @deprecated use `UserGetUserLiteRequest$inboundSchema` instead. */
  export const inboundSchema = UserGetUserLiteRequest$inboundSchema;
  /** @deprecated use `UserGetUserLiteRequest$outboundSchema` instead. */
  export const outboundSchema = UserGetUserLiteRequest$outboundSchema;
  /** @deprecated use `UserGetUserLiteRequest$Outbound` instead. */
  export type Outbound = UserGetUserLiteRequest$Outbound;
}

export function userGetUserLiteRequestToJSON(
  userGetUserLiteRequest: UserGetUserLiteRequest,
): string {
  return JSON.stringify(
    UserGetUserLiteRequest$outboundSchema.parse(userGetUserLiteRequest),
  );
}
export function userGetUserLiteRequestFromJSON(
  jsonString: string,
): SafeParseResult<UserGetUserLiteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGetUserLiteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGetUserLiteRequest' from JSON`,
  );
}
