/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UserGetUsersByCountryRequest = {
  countryId: string;
  limit?: number | undefined;
  cursor?: string | undefined;
};

/** @internal */
export type UserGetUsersByCountryRequest$Outbound = {
  countryId: string;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const UserGetUsersByCountryRequest$outboundSchema: z.ZodMiniType<
  UserGetUsersByCountryRequest$Outbound,
  UserGetUsersByCountryRequest
> = z.object({
  countryId: z.string(),
  limit: z._default(z.number(), 10),
  cursor: z.optional(z.string()),
});

export function userGetUsersByCountryRequestToJSON(
  userGetUsersByCountryRequest: UserGetUsersByCountryRequest,
): string {
  return JSON.stringify(
    UserGetUsersByCountryRequest$outboundSchema.parse(
      userGetUsersByCountryRequest,
    ),
  );
}
