/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkOfferGetByIdInput = {
  workOfferId: string;
};

export type WorkOfferGetByIdRequest = {
  /**
   * JSON-encoded input parameters
   */
  input: WorkOfferGetByIdInput;
};

/** @internal */
export const WorkOfferGetByIdInput$inboundSchema: z.ZodMiniType<
  WorkOfferGetByIdInput,
  unknown
> = z.object({
  workOfferId: types.string(),
});
/** @internal */
export type WorkOfferGetByIdInput$Outbound = {
  workOfferId: string;
};

/** @internal */
export const WorkOfferGetByIdInput$outboundSchema: z.ZodMiniType<
  WorkOfferGetByIdInput$Outbound,
  WorkOfferGetByIdInput
> = z.object({
  workOfferId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkOfferGetByIdInput$ {
  /** @deprecated use `WorkOfferGetByIdInput$inboundSchema` instead. */
  export const inboundSchema = WorkOfferGetByIdInput$inboundSchema;
  /** @deprecated use `WorkOfferGetByIdInput$outboundSchema` instead. */
  export const outboundSchema = WorkOfferGetByIdInput$outboundSchema;
  /** @deprecated use `WorkOfferGetByIdInput$Outbound` instead. */
  export type Outbound = WorkOfferGetByIdInput$Outbound;
}

export function workOfferGetByIdInputToJSON(
  workOfferGetByIdInput: WorkOfferGetByIdInput,
): string {
  return JSON.stringify(
    WorkOfferGetByIdInput$outboundSchema.parse(workOfferGetByIdInput),
  );
}
export function workOfferGetByIdInputFromJSON(
  jsonString: string,
): SafeParseResult<WorkOfferGetByIdInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkOfferGetByIdInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkOfferGetByIdInput' from JSON`,
  );
}

/** @internal */
export const WorkOfferGetByIdRequest$inboundSchema: z.ZodMiniType<
  WorkOfferGetByIdRequest,
  unknown
> = z.object({
  input: z.lazy(() => WorkOfferGetByIdInput$inboundSchema),
});
/** @internal */
export type WorkOfferGetByIdRequest$Outbound = {
  input: WorkOfferGetByIdInput$Outbound;
};

/** @internal */
export const WorkOfferGetByIdRequest$outboundSchema: z.ZodMiniType<
  WorkOfferGetByIdRequest$Outbound,
  WorkOfferGetByIdRequest
> = z.object({
  input: z.lazy(() => WorkOfferGetByIdInput$outboundSchema),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkOfferGetByIdRequest$ {
  /** @deprecated use `WorkOfferGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = WorkOfferGetByIdRequest$inboundSchema;
  /** @deprecated use `WorkOfferGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = WorkOfferGetByIdRequest$outboundSchema;
  /** @deprecated use `WorkOfferGetByIdRequest$Outbound` instead. */
  export type Outbound = WorkOfferGetByIdRequest$Outbound;
}

export function workOfferGetByIdRequestToJSON(
  workOfferGetByIdRequest: WorkOfferGetByIdRequest,
): string {
  return JSON.stringify(
    WorkOfferGetByIdRequest$outboundSchema.parse(workOfferGetByIdRequest),
  );
}
export function workOfferGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<WorkOfferGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkOfferGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkOfferGetByIdRequest' from JSON`,
  );
}
