/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type WorkOfferGetWorkOfferByCompanyIdRequest = {
  companyId: string;
};

/** @internal */
export type WorkOfferGetWorkOfferByCompanyIdRequest$Outbound = {
  companyId: string;
};

/** @internal */
export const WorkOfferGetWorkOfferByCompanyIdRequest$outboundSchema:
  z.ZodMiniType<
    WorkOfferGetWorkOfferByCompanyIdRequest$Outbound,
    WorkOfferGetWorkOfferByCompanyIdRequest
  > = z.object({
    companyId: z.string(),
  });

export function workOfferGetWorkOfferByCompanyIdRequestToJSON(
  workOfferGetWorkOfferByCompanyIdRequest:
    WorkOfferGetWorkOfferByCompanyIdRequest,
): string {
  return JSON.stringify(
    WorkOfferGetWorkOfferByCompanyIdRequest$outboundSchema.parse(
      workOfferGetWorkOfferByCompanyIdRequest,
    ),
  );
}
