/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkOfferGetWorkOfferByCompanyIdInput = {
  companyId: string;
};

export type WorkOfferGetWorkOfferByCompanyIdRequest = {
  /**
   * JSON-encoded input parameters
   */
  input: WorkOfferGetWorkOfferByCompanyIdInput;
};

/** @internal */
export const WorkOfferGetWorkOfferByCompanyIdInput$inboundSchema: z.ZodMiniType<
  WorkOfferGetWorkOfferByCompanyIdInput,
  unknown
> = z.object({
  companyId: types.string(),
});
/** @internal */
export type WorkOfferGetWorkOfferByCompanyIdInput$Outbound = {
  companyId: string;
};

/** @internal */
export const WorkOfferGetWorkOfferByCompanyIdInput$outboundSchema:
  z.ZodMiniType<
    WorkOfferGetWorkOfferByCompanyIdInput$Outbound,
    WorkOfferGetWorkOfferByCompanyIdInput
  > = z.object({
    companyId: z.string(),
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkOfferGetWorkOfferByCompanyIdInput$ {
  /** @deprecated use `WorkOfferGetWorkOfferByCompanyIdInput$inboundSchema` instead. */
  export const inboundSchema =
    WorkOfferGetWorkOfferByCompanyIdInput$inboundSchema;
  /** @deprecated use `WorkOfferGetWorkOfferByCompanyIdInput$outboundSchema` instead. */
  export const outboundSchema =
    WorkOfferGetWorkOfferByCompanyIdInput$outboundSchema;
  /** @deprecated use `WorkOfferGetWorkOfferByCompanyIdInput$Outbound` instead. */
  export type Outbound = WorkOfferGetWorkOfferByCompanyIdInput$Outbound;
}

export function workOfferGetWorkOfferByCompanyIdInputToJSON(
  workOfferGetWorkOfferByCompanyIdInput: WorkOfferGetWorkOfferByCompanyIdInput,
): string {
  return JSON.stringify(
    WorkOfferGetWorkOfferByCompanyIdInput$outboundSchema.parse(
      workOfferGetWorkOfferByCompanyIdInput,
    ),
  );
}
export function workOfferGetWorkOfferByCompanyIdInputFromJSON(
  jsonString: string,
): SafeParseResult<WorkOfferGetWorkOfferByCompanyIdInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WorkOfferGetWorkOfferByCompanyIdInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkOfferGetWorkOfferByCompanyIdInput' from JSON`,
  );
}

/** @internal */
export const WorkOfferGetWorkOfferByCompanyIdRequest$inboundSchema:
  z.ZodMiniType<WorkOfferGetWorkOfferByCompanyIdRequest, unknown> = z.object({
    input: z.lazy(() => WorkOfferGetWorkOfferByCompanyIdInput$inboundSchema),
  });
/** @internal */
export type WorkOfferGetWorkOfferByCompanyIdRequest$Outbound = {
  input: WorkOfferGetWorkOfferByCompanyIdInput$Outbound;
};

/** @internal */
export const WorkOfferGetWorkOfferByCompanyIdRequest$outboundSchema:
  z.ZodMiniType<
    WorkOfferGetWorkOfferByCompanyIdRequest$Outbound,
    WorkOfferGetWorkOfferByCompanyIdRequest
  > = z.object({
    input: z.lazy(() => WorkOfferGetWorkOfferByCompanyIdInput$outboundSchema),
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkOfferGetWorkOfferByCompanyIdRequest$ {
  /** @deprecated use `WorkOfferGetWorkOfferByCompanyIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    WorkOfferGetWorkOfferByCompanyIdRequest$inboundSchema;
  /** @deprecated use `WorkOfferGetWorkOfferByCompanyIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    WorkOfferGetWorkOfferByCompanyIdRequest$outboundSchema;
  /** @deprecated use `WorkOfferGetWorkOfferByCompanyIdRequest$Outbound` instead. */
  export type Outbound = WorkOfferGetWorkOfferByCompanyIdRequest$Outbound;
}

export function workOfferGetWorkOfferByCompanyIdRequestToJSON(
  workOfferGetWorkOfferByCompanyIdRequest:
    WorkOfferGetWorkOfferByCompanyIdRequest,
): string {
  return JSON.stringify(
    WorkOfferGetWorkOfferByCompanyIdRequest$outboundSchema.parse(
      workOfferGetWorkOfferByCompanyIdRequest,
    ),
  );
}
export function workOfferGetWorkOfferByCompanyIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkOfferGetWorkOfferByCompanyIdRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkOfferGetWorkOfferByCompanyIdRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkOfferGetWorkOfferByCompanyIdRequest' from JSON`,
  );
}
