/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type WorkOfferGetByIdRequest = {
  workOfferId: string;
};

/** @internal */
export type WorkOfferGetByIdRequest$Outbound = {
  workOfferId: string;
};

/** @internal */
export const WorkOfferGetByIdRequest$outboundSchema: z.ZodMiniType<
  WorkOfferGetByIdRequest$Outbound,
  WorkOfferGetByIdRequest
> = z.object({
  workOfferId: z.string(),
});

export function workOfferGetByIdRequestToJSON(
  workOfferGetByIdRequest: WorkOfferGetByIdRequest,
): string {
  return JSON.stringify(
    WorkOfferGetByIdRequest$outboundSchema.parse(workOfferGetByIdRequest),
  );
}
