/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkOfferGetWorkOffersPaginatedRequest = {
  userId?: string | undefined;
  regionId?: string | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const WorkOfferGetWorkOffersPaginatedRequest$inboundSchema:
  z.ZodMiniType<WorkOfferGetWorkOffersPaginatedRequest, unknown> = z.object({
    userId: types.optional(types.string()),
    regionId: types.optional(types.string()),
    cursor: types.optional(types.string()),
    limit: z._default(types.number(), 10),
  });
/** @internal */
export type WorkOfferGetWorkOffersPaginatedRequest$Outbound = {
  userId?: string | undefined;
  regionId?: string | undefined;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const WorkOfferGetWorkOffersPaginatedRequest$outboundSchema:
  z.ZodMiniType<
    WorkOfferGetWorkOffersPaginatedRequest$Outbound,
    WorkOfferGetWorkOffersPaginatedRequest
  > = z.object({
    userId: z.optional(z.string()),
    regionId: z.optional(z.string()),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 10),
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkOfferGetWorkOffersPaginatedRequest$ {
  /** @deprecated use `WorkOfferGetWorkOffersPaginatedRequest$inboundSchema` instead. */
  export const inboundSchema =
    WorkOfferGetWorkOffersPaginatedRequest$inboundSchema;
  /** @deprecated use `WorkOfferGetWorkOffersPaginatedRequest$outboundSchema` instead. */
  export const outboundSchema =
    WorkOfferGetWorkOffersPaginatedRequest$outboundSchema;
  /** @deprecated use `WorkOfferGetWorkOffersPaginatedRequest$Outbound` instead. */
  export type Outbound = WorkOfferGetWorkOffersPaginatedRequest$Outbound;
}

export function workOfferGetWorkOffersPaginatedRequestToJSON(
  workOfferGetWorkOffersPaginatedRequest:
    WorkOfferGetWorkOffersPaginatedRequest,
): string {
  return JSON.stringify(
    WorkOfferGetWorkOffersPaginatedRequest$outboundSchema.parse(
      workOfferGetWorkOffersPaginatedRequest,
    ),
  );
}
export function workOfferGetWorkOffersPaginatedRequestFromJSON(
  jsonString: string,
): SafeParseResult<WorkOfferGetWorkOffersPaginatedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WorkOfferGetWorkOffersPaginatedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkOfferGetWorkOffersPaginatedRequest' from JSON`,
  );
}
