/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type WorkOfferGetWorkOffersPaginatedRequest = {
  userId?: string | undefined;
  regionId?: string | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export type WorkOfferGetWorkOffersPaginatedRequest$Outbound = {
  userId?: string | undefined;
  regionId?: string | undefined;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const WorkOfferGetWorkOffersPaginatedRequest$outboundSchema:
  z.ZodMiniType<
    WorkOfferGetWorkOffersPaginatedRequest$Outbound,
    WorkOfferGetWorkOffersPaginatedRequest
  > = z.object({
    userId: z.optional(z.string()),
    regionId: z.optional(z.string()),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 10),
  });

export function workOfferGetWorkOffersPaginatedRequestToJSON(
  workOfferGetWorkOffersPaginatedRequest:
    WorkOfferGetWorkOffersPaginatedRequest,
): string {
  return JSON.stringify(
    WorkOfferGetWorkOffersPaginatedRequest$outboundSchema.parse(
      workOfferGetWorkOffersPaginatedRequest,
    ),
  );
}
